mmcService - Interactive MODS Mechanism Control System: blueIMCS.cpp File Reference
blueIMCS.cpp File Reference
MODS Blue Channel IMCS program.
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <cstdlib>
#include <modbus.h>
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/sendfile.h>
#include <time.h>
#include "system_dep.h"
#include "instrutils.h"
#include "isl_funcs.h"
#include "isl_types.h"
#include "params.h"
#include "islcommon.h"
#include "isl_shmaddr.h"
#include "mmccontrol.h"
#include "islapi.h"
Macros
#define MAX_WAGO 6
#define MAX_WRITE_ERRORS 10
Functions
char * getDateTime (void)
Return the UTC date/time as an ISO 8601 coded string.
int getMechanismID (char mechanism_name[], char dummy[])
Get the mechanism ID from Shared Memory.
int getQCID (char qc_name[], char dummy[])
Get the quad cell system ID from Shared Memory.
int bcolfoc_to (char *, char[], char[], long)
int getWagoQC (char *wagoAddr, int regAddr, int *rawData)
Readout the IMCS quad cell board using a WAGO modbus/TCP system.
float qc2vdc (int rawQC)
Convert raw quad cell ADC datum to DC volts.
int main (int argc, char *argv[])
main program
void HandleInt (int signalValue)
Handle Ctrl+C Interrupts (SIGINT)
Variables
const int RCVBUFSIZE = 24
int bimcsWAGO
int bTTFA
int bTTFB
int bTTFC
Detailed Description
MODS Blue Channel IMCS program.
Macro Definition Documentation
MAX_WAGO
#define MAX_WAGO 6
MAX_WRITE_ERRORS
#define MAX_WRITE_ERRORS 10
Function Documentation
getDateTime()
char * getDateTime (void)
Return the UTC date/time as an ISO 8601 coded string.
Reads the system time clock and returns the UTC date and time coded as an ASCII string in ISO 6801 compliant format (www.iso.org/iso/iso8601). The UTC clock time is expressed to microsecond precision (we make no claims to microsecond accuracy - YMMV). For example
  2013-05-26T12:07:58.114391
Referenced by HandleInt(), and main().
getMechanismID()
int getMechanismID (char mechanism_name[], char dummy[])
Get the mechanism ID from Shared Memory.
Parameters
mechanism_name name of the mechanism
reply message string for errors)
Returns
integer mechanism ID code or -1 on errors
Get the integer Mechanism ID code corresponding to a named mechanism.
Referenced by cmd_abort(), cmd_agw(), cmd_agwfilt(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_calib(), cmd_camfoc(), cmd_close(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gprobe(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_ieb(), cmd_imcs(), cmd_istatus(), cmd_minsert(), cmd_misc(), cmd_moveabs(), cmd_moverel(), cmd_mselect(), cmd_mstatus(), cmd_open(), cmd_shutter(), cmd_slitmask(), main(), and thread_init_func().
getQCID()
int getQCID (char qc_name[], char dummy[])
Get the quad cell system ID from Shared Memory.
Parameters
qc_name name of the IMCS quad cell system in shared memory
reply message string for errors
Returns
integer QC unit ID code or -1 on errors
Get the integer ID code corresponding to a named WAGO-based IMCS quad cell system. This ID code is used to get the IP address and analog input module register address from shared memory.
Referenced by main().
bcolfoc_to()
int bcolfoc_to (char * host, char str[], char str1[], long timeout)
References ierr.
Referenced by main().
getWagoQC()
int getWagoQC (char * wagoAddr, int regAddr, int * rawData)
Readout the IMCS quad cell board using a WAGO modbus/TCP system.
Parameters
wagoAddr (char*) The address of the WAGO device to query
regAddr (int) register address (range: 1 - 0x10000)
rawData (uint16) array of data to read
Returns
0 on send success, value or error code on faults
We have adopted opensource libmodbus to replace the replace the defunct and unsupported proprietary FieldTalk code used in the original MODS system.
Author: Xander Carroll & Rick Pogge, OSU Astronomy Dept: Updated: 2025 June 28 - based on modbusutils.c for the modsHEB agent
Referenced by main().
qc2vdc()
float qc2vdc (int rawQC)
Convert raw quad cell ADC datum to DC volts.
Parameters
rawQC integer with raw quad cell ADC value (0..2^15-1)
Convenience function to convert raw WAGO analog input module ADC out datum to DC volts. Assumes the WAGO 750-471 module is properly configured for -10..10VDC conversion
Output is a floating-point voltage. Discretization is ~0.3mVDC
Referenced by main().
main()
int main (int argc, char * argv[])
main program
References bcolfoc_to(), bimcsWAGO, bTTFA, bTTFB, bTTFC, getDateTime(), getMechanismID(), getQCID(), getWagoQC(), HandleInt(), ierr, qc2vdc(), and RCVBUFSIZE.
HandleInt()
void HandleInt (int signalValue)
Handle Ctrl+C Interrupts (SIGINT)
Parameters
signalValue integer value passed by the SIGINT signal catcher
At this point all we do is print that the process has been halted by a Ctrl+C/SIGINT signal and exit gracefully.
Later we might add more shutdown handling, but so far none appears indicated.
References getDateTime().
Referenced by KeyCommand(), and main().
Variable Documentation
RCVBUFSIZE
const int RCVBUFSIZE = 24
Referenced by main().
bimcsWAGO
int bimcsWAGO
Referenced by main().
bTTFA
int bTTFA
Referenced by main().
bTTFB
int bTTFB
Referenced by main().
bTTFC
int bTTFC
Referenced by main().