mmcService - Interactive MODS Mechanism Control System: commands.c File Reference
commands.c File Reference
MODS mechanism control server (mmcServer, aka Mn.IE host) commands.
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <sys/wait.h>
#include <time.h>
#include <errno.h>
#include "instrutils.h"
#include "isl_funcs.h"
#include "mmc_client.h"
#include "mmc_commands.h"
#include "isl_types.h"
#include "isl_shmaddr.h"
#include "islcommon.h"
#include "modscontrol.h"
#include "mmccontrol.h"
#include "./mlc.c"
#include <readline/readline.h>
#include <readline/history.h>
Macros
#define BI_STATE 0
#define LINEAR 1
#define INDEXED 2
#define VISPOUTWAGO 1
#define IRPOUTWAGO 2
#define IRTSETWAGO 3
#define IRTOUTWAGO 4
#define VISPSETWAGO 513
#define IRPSETWAGO 514
#define VFLATPSET 515
#define OPENADDR 516
#define LLBONOFF 517
#define MAXPGMLINE 80
Functions
int wagoSetGet (int gs, char *host, int slaveAddr, int startRef, short regArr[], int refCnt)
int itoa (int, char[])
void StrUpper (char *)
Convert all characters in a string to uppercase.
int logLampParam (char *, int[], int[])
int getCurrentTime (char *, char *)
int mmcLOGGER (char[], char[])
int cmd_quit (char *args, MsgType msgtype, char *reply)
QUIT command - quit the client session.
int cmd_ping (char *args, MsgType msgtype, char *reply)
PING command - communication handshaking request.
int cmd_pong (char *args, MsgType msgtype, char *reply)
PONG command - communication handshaking acknowledgment.
int cmd_version (char *args, MsgType msgtype, char *reply)
VERSION command - report application version and compilation info.
int cmd_verbose (char *args, MsgType msgtype, char *reply)
VERBOSE command - toggle verbose console output on/off.
int cmd_debug (char *args, MsgType msgtype, char *reply)
DEBUG command - toggle debugging (super-verbose) console output on/off.
int cmd_info (char *args, MsgType msgtype, char *reply)
INFO command - report client application runtime information.
int cmd_help (char *args, MsgType msgtype, char *reply)
HELP command - print a list of commands on the client console.
int cmd_mstatus (char *args, MsgType msgtype, char *reply)
MSTATUS command - report client mechanism status.
int cmd_istatus (char *args, MsgType msgtype, char *reply)
ISTATUS command - report general status.
int cmd_pstatus (char *args, MsgType msgtype, char *reply)
PSTATUS command - report power status.
int cmd_ports (char *args, MsgType msgtype, char *reply)
PORTS command - report info about open comm ports.
int cmd_misc (char *args, MsgType msgtype, char *reply)
Miscellaneous commands that don't fit anywhere else.
int cmd_open (char *args, MsgType msgtype, char *reply)
OPEN command - open all or 1 comm port.
int cmd_close (char *args, MsgType msgtype, char *reply)
CLOSE command - close a comm port re-initialize the microstep drive.
int cmd_setport (char *args, MsgType msgtype, char *reply)
SETPORT command - set/query comm port attributes re-initialize the microstep drive.
int cmd_moverel (char *args, MsgType msgtype, char *reply)
moverel command - relative move command +/-value
int cmd_moveabs (char *args, MsgType msgtype, char *reply)
moveabs command - absolute command move
int cmd_hatch (char *args, MsgType msgtype, char *reply)
hatch command - command the hatch to Open or Close
int cmd_calib (char *args, MsgType msgtype, char *reply)
calib command - command the Calibration Tower
int cmd_minsert (char *args, MsgType msgtype, char *reply)
minsert command - command the Insert Mask mechanism
int cmd_mselect (char *args, MsgType msgtype, char *reply)
mselect command - command the Mask Select mechanism
int cmd_slitmask (char *args, MsgType msgtype, char *reply)
slitmask command - command the slit mask for deployment
int cmd_agw (char *args, MsgType msgtype, char *reply)
AGW command - Configure the AGW stage.
int cmd_agwy (char *args, MsgType msgtype, char *reply)
agwY command - AGW Stage Y-axis position
int cmd_agwx (char *args, MsgType msgtype, char *reply)
agwX command - AGW Stage X-axis position
int cmd_agwfoc (char *args, MsgType msgtype, char *reply)
agwfoc command - AGW Stage Focus Position
int cmd_agwfilt (char *args, MsgType msgtype, char *reply)
agwfilt command - AGW Guide Camera Filter Wheel
int cmd_dichroic (char *args, MsgType msgtype, char *reply)
dichroic command - command the Dichroic
int cmd_gprobe (char *args, MsgType msgtype, char *reply)
gprobe command - Move AGW guide probe to an absolute X,Y position
int cmd_gpoffset (char *args, MsgType msgtype, char *reply)
gpoffset command - Offset the AGW guide probe deltaX, deltaY
int cmd_gpfocus (char *args, MsgType msgtype, char *reply)
gpfocus command - AGW Probe Focus Position
int cmd_colttf (char *args, MsgType msgtype, char *reply)
colttf command - Set a collimator mirror tip/tilt/focus actuator
int cmd_colfoc (char *args, MsgType msgtype, char *reply)
colttf command - Set the collimator mirror absolute focus position
int cmd_grating (char *args, MsgType msgtype, char *reply)
grating command - Select a grating in the grating turret
int cmd_grtilt (char *args, MsgType msgtype, char *reply)
grating command - Tilt grating n to a given absolute tilt
int cmd_shutter (char *args, MsgType msgtype, char *reply)
shutter command - Open/Close the camera shutter
int cmd_camfoc (char *args, MsgType msgtype, char *reply)
camfoc command - Focus the camera primary mirror
int cmd_filter (char *args, MsgType msgtype, char *reply)
filter command - Select a filter on the filter wheel
int cmd_lamp (char *args, MsgType msgtype, char *reply)
lamp command - Operate the calibration lamps
int cmd_vislaser (char *args, MsgType msgtype, char *reply)
vislaser command - Operate the IMCS Visible-light Alignment Laser
int cmd_irlaser (char *args, MsgType msgtype, char *reply)
irlaser command - Operate the IMCS Infrared Reference Laser
int cmd_abort (char *args, MsgType msgtype, char *reply)
ABORT command - abort all one or more mechanisms.
int cmd_power65 (char *args, MsgType msgtype, char *reply)
POWER65 command - Turn on/off 65 VDC power supply.
int cmd_ieb (char *args, MsgType msgtype, char *reply)
ieb command - IEB interface
int cmd_imcs (char *args, MsgType msgtype, char *reply)
IMCS command - report quadcells Open/Close loop.
int cmd_loadplc (char *args, MsgType msgtype, char *reply)
LOADPLC command - load MicroLYNX controller with Ladder code.
void KeyCommand (char *line, char reply[])
Process a command from the client's console keyboard.
void SocketCommand (char *buf)
Process a message/command from a remote ISIS server/client application.
float findPoly (float x, float *a, int n)
double dfindPoly (double x, double *a, int n)
Variables
char argbuf [MAXPGMLINE]
int commandID
char * mods_fatalerrormsg []
char who_srcID [MAXPGMLINE]
int llbID
int utilID
int ieb1ID
int ieb2ID
int ierr
int he_token =1
char inbuf [MAXPGMLINE]
FILE * pgmFP
Detailed Description
MODS mechanism control server (mmcServer, aka Mn.IE host) commands.
This module contains the command "action" functions called to service the MODS IE commands. These consist of a suite of
"common" client action functions common to most ISIS clients
client-specific functions that perform the client's particular tasks
common interface routines for keyboard and ISIS socket interfaces.
The common client commands include the following:
These 3 commands are REQUIRED of all ISIS client apps:
cmd_quit() terminate a client session (QUIT)
cmd_ping() communications handshaking request (PING) from a remote ISIS node
cmd_pong() communications handshaking acknowledgment (PONG) from a remote ISIS node
These client commands are recommended for most apps:
cmd_version() Report application version information (VERSION)
cmd_info() Report client runtime configuration (INFO, sometimes CONFIG in legacy apps).
These are common commands relevant for the CLI, but generally not available to remote ISIS nodes (e.g., they test that the message type is EXEC:):
cmd_verbose() Toggle verbose output to the client console on/off (VERBOSE)
cmd_debug() Toggle debugging (super-verbose) output to console on/off (DEBUG)
cmd_help() List interactive client commands (HELP or ?)
cmd_history() Print the recent interactive command history (HISTORY)
These are then followed by cmd_xxx() action functions that implement the various client tasks.
At the end of this file are the template I/O handlers used by the command interpreter:
KeyboardCommand() Keyboard command handler (command-line interface)
SocketCommand() Socket command/message handler (client socket interface)
Author
R. Pogge, OSU Astronomy Dept. (pogge.nosp@m.@ast.nosp@m.ronom.nosp@m.y.oh.nosp@m.io-st.nosp@m.ate..nosp@m.edu)
Date
2003 October 13
2005 March 20 Many features added. (rdg)
2009 April/May - refinements during MODS1 lab integration and testing (rdg/tja/rwp)
2010 & 2011 - bug fixes during MODS1 at LBT commissioning [rwp/rdg]
2012 Feb - major bug in OBSMODE that zeroed IMCS laser power fixed [rwp]
2025 Jun 20 - AlmaLinux 9 port [rwp/osu]
Macro Definition Documentation
BI_STATE
#define BI_STATE 0
LINEAR
#define LINEAR 1
INDEXED
#define INDEXED 2
VISPOUTWAGO
#define VISPOUTWAGO 1
IRPOUTWAGO
#define IRPOUTWAGO 2
IRTSETWAGO
#define IRTSETWAGO 3
IRTOUTWAGO
#define IRTOUTWAGO 4
VISPSETWAGO
#define VISPSETWAGO 513
IRPSETWAGO
#define IRPSETWAGO 514
VFLATPSET
#define VFLATPSET 515
OPENADDR
#define OPENADDR 516
LLBONOFF
#define LLBONOFF 517
MAXPGMLINE
#define MAXPGMLINE 80
Function Documentation
wagoSetGet()
int wagoSetGet (int gs, char * host, int slaveAddr, int startRef, short regArr[], int refCnt)
Referenced by cmd_ieb(), cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_misc(), cmd_power65(), cmd_vislaser(), mlcPANIC(), and wagoRW().
itoa()
int itoa (int , char [])
StrUpper()
void StrUpper (char * str)
Convert all characters in a string to uppercase.
Parameters
str String to be converted to uppercase. Changed by this function.
Helper utility to convert all characters in a string to uppercase. All commands are required to be in uppercase.
Referenced by cmd_abort(), cmd_agw(), cmd_agwfilt(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_calib(), cmd_camfoc(), cmd_close(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gpoffset(), cmd_gprobe(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_help(), cmd_ieb(), cmd_imcs(), cmd_info(), cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_minsert(), cmd_misc(), cmd_moveabs(), cmd_moverel(), cmd_mselect(), cmd_mstatus(), cmd_open(), cmd_ports(), cmd_power65(), cmd_pstatus(), cmd_setport(), cmd_shutter(), cmd_slitmask(), cmd_version(), cmd_vislaser(), main(), and SocketCommand().
logLampParam()
int logLampParam (char * , int [], int [])
getCurrentTime()
int getCurrentTime (char * , char *)
mmcLOGGER()
int mmcLOGGER (char [], char [])
Referenced by cmd_grtilt(), cmd_misc(), and SocketCommand().
cmd_quit()
int cmd_quit (char * args, MsgType msgtype, char * reply)
QUIT command - quit the client session.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK if command executed without errors, #CMD_ERR if an error occurred. On errors reply contains the error message.
Usage:
quit
Executes the application QUIT command. Only works if msgtype=EXEC, indicating that it is an IMPv2 executive command. This prevents remote applications from prematurely terminating this application by sending a QUIT command unqualified by the EXEC: directive.
References client.
cmd_ping()
int cmd_ping (char * args, MsgType msgtype, char * reply)
PING command - communication handshaking request.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK if command executed without errors, #CMD_ERR if an error occurred. On errors reply contains the error message.
This function is invoked when the client application receives a PING from a remote host requesting a communications handshaking reply.
PINGs are actually handled separately in the SocketCommand() handler (nothing is done by the KeyboardCommand() handler) because the PONG sent back acknowledging the comm handshaking request is, in effect, a pseudo-command (implicit REQ:), not a "DONE:" response to a command request. This exception to the general messaging syntax has to be handled carefully to prevent problems, especially to ensure backwards compatibility with older IMPv applications.
See also
cmd_pong
cmd_pong()
int cmd_pong (char * args, MsgType msgtype, char * reply)
PONG command - communication handshaking acknowledgment.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_NOOP since PONG is a no-op pseudo command.
For historical reasons, a "PONG" sent in acknowledgment of a software handshaking "PING" looks like an implicit REQ:, and hence like a "command request" sent to the recipient, even though it isn't. It is, however, an exception to the strict messaging protocol, which is why it needs a separate handler.
cmd_pong doesn't do anything except return a #CMD_NOOP (since this "command" must NOT result in a reply back to the sender). In more sophisticated apps, we might actually use receipt of a pong to do something useful (e.g., help build up a node table), so at the very least this module works as a placeholder for future expansion.
See also
cmd_ping
References client.
cmd_version()
int cmd_version (char * args, MsgType msgtype, char * reply)
VERSION command - report application version and compilation info.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK
Usage:
version
Creates an IMPv2 message (in the reply string) with the version number and any relevant compilation information (e.g., date and time of compilation). VERSION allows a way for users or remote apps to verify the runtime version of the current application.
Example output:
Version=v1.0 CompileDate=2004-Jun-11 CompileTime=17:08:15
References commandID, ierr, and StrUpper().
cmd_verbose()
int cmd_verbose (char * args, MsgType msgtype, char * reply)
VERBOSE command - toggle verbose console output on/off.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK
Usage:
verbose
Sets the client isVerbose flag to 1 (enabled) if currently 0 (disabled) and vis-versa. Verbose output mode is used for basic client debugging information by printing extra information on the application console screen. Disabling throttles verbose console output. VERBOSE mode is normally disabled during normal operations.
In general "Verbose" output refers only to client application level output (i.e., echoing socket message traffic, printing status update info, etc.). An more chatty DEBUG mode is provided that prints more engineering-level info for detailed low-level system debugging.
See also
cmd_debug
References client.
cmd_debug()
int cmd_debug (char * args, MsgType msgtype, char * reply)
DEBUG command - toggle debugging (super-verbose) console output on/off.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK
Usage:
debug
Sets the client Debug flag to 1 (enabled) if currently 0 (disabled) and vis-versa.
DEBUG mode is a super-verbose mode that spews lots of I/O chatter onto the application console, useful during client debugging or for troubleshooting. For example, in client applications that control stepper motors, the full motor control chatter is echoed to the console during DEBUG mode to enable the user to follow the steps the system is (or is not) taking, watch encoder and limit switches assert (or not), etc. DEBUG is normally disabled during normal user operations.
See also
cmd_verbose
References client.
cmd_info()
int cmd_info (char * args, MsgType msgtype, char * reply)
INFO command - report client application runtime information.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on successful creation of the info report, #CMD_ERR if errors encountered.
Usage:
info (alias: status)
Creates a summary report of the current client application's runtime configuration as an IMPv2-compliant message string in which the runtime parameters are reported as keyword=value pairs.
The format of cmd_info should be tailored specifically for the particular client application. If a client controls specific instrument or interface functions, the state of those functions should be reported in the info string, making it an omnibus "what is your status" command.
References client, commandID, and StrUpper().
cmd_help()
int cmd_help (char * args, MsgType msgtype, char * reply)
HELP command - print a list of commands on the client console.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_NOOP on success, #CMD_ERR if help executed as a non-EXEC: command
Usage:
help [cmd]
cmd_help is usually invoked by the HELP or ? commands. It prints a list of all interactive commands on the client application's console screen. It is only meant to be executed as an EXEC: message type. If the command is not qualifed as EXEC:, it returns an error.
If an argument is given, it tries to find that string in the command list, and if successful, prints a brief description and usage message.
Help is meant to be simple. It can give help on particular commands (really a reminder of the command's function and syntax), or a list of all commands.
References argbuf, makeUpper(), and StrUpper().
cmd_mstatus()
int cmd_mstatus (char * args, MsgType msgtype, char * reply)
MSTATUS command - report client mechanism status.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
References argbuf, commandID, getMechanismID(), ierr, mlcQuery(), rawCommand(), and StrUpper().
cmd_istatus()
int cmd_istatus (char * args, MsgType msgtype, char * reply)
ISTATUS command - report general status.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: ISTATUS
Description:
Returns the current states of all instrument mechanisms, lamps, and lasers providing a comprehensive snapshot of the current instrument configuration in the form of FITS-style keyword=value pairs.
The ICs (red and blue) will issue ISTATUS queries to the IE before each exposure to create the instrument-related FITS header entries for that exposure, and user interface programs will issue ISTATUS commands to update their status displays.
The main purpose of ISTATUS is to report the positions of all instrument mechanisms(filter wheels, focus positions, etc.). These define the most important instrument configuration parameters vis--vis observing that must appear in each image FITS headers.
ISTATUS returns only the most relevant subset of instrument power state keywords,namely the global power state of the IEBs, LLB, AGW controllers, and HEBs, and the power states of the calibration lamps (CALLAMPS=) and the IMCS IR laser. For detailed power status, use the PSTATUS command.
References commandID, getMechanismID(), getWagoID(), ierr, KeyCommand(), llbID, LLBONOFF, StrUpper(), utilID, and wagoSetGet().
Referenced by cmd_misc().
cmd_pstatus()
int cmd_pstatus (char * args, MsgType msgtype, char * reply)
PSTATUS command - report power status.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
return #CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: PSTATUS
Description:
PSTATUS returns the current instrument power state including the power states of all lamps and lasers controlled by the IE. The command response is a combination of the status replies returned by the IEB, LLB, and UTIL status queries implemented as a single command. It only returns power status variables, no other non-power information (e.g.,report if the IR laser AC power is on/off, but do not report beam enable/disable, power status, laser head temperatures, etc.).
References cmd_lamp(), commandID, ierr, StrUpper(), and wagoRW().
cmd_ports()
int cmd_ports (char * args, MsgType msgtype, char * reply)
PORTS command - report info about open comm ports.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
ports
Report information about all comm ports connected to the client in IMPv2-compliant format. Shows their status as follows:
CommPort=/dev/ttyS0 Open
References commandID, and StrUpper().
cmd_misc()
int cmd_misc (char * args, MsgType msgtype, char * reply)
Miscellaneous commands that don't fit anywhere else.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
cmd_misc() is a place to put commands that don't fit anywhere else, or that are experimental before committing to their own cmd_xyz() function.
util [status] [service1 service2... [on|off]] [all off] [glycol] [temp] serviceN - name(s) of switched AC power service [e.g.,IEB_B, LLB ...] status - report status on|off - power service(s) on or off all off - power all services off glycol - report glycol supply and return temperature and pressure data temp - replort Utility Box temperature sensor(RTD) date.
llb - lamp/laser box services
calmode - put instrument in calibration mode (AGW out, calib tower in, hatch closed)
obsmode - put instrument in observing mode (calib tower out, AGW in, hatch open)
estatus - environmental sensor status summary
References agwProbe(), agwRestore(), argbuf, Calib(), cmd_istatus(), commandID, getMechanismID(), getWagoID(), Hatch(), ierr, isisStatusMsg(), KeyCommand(), llbID, LLBONOFF, mlcBitsBase10(), mmcLOGGER(), StrUpper(), utilID, and wagoSetGet().
cmd_open()
int cmd_open (char * args, MsgType msgtype, char * reply)
OPEN command - open all or 1 comm port.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
open [n|all]
Opens all or a named comm port.
References argbuf, commandID, getMechanismID(), ierr, and StrUpper().
cmd_close()
int cmd_close (char * args, MsgType msgtype, char * reply)
CLOSE command - close a comm port re-initialize the microstep drive.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
close port
Closes a named comm port.
References argbuf, commandID, getMechanismID(), ierr, and StrUpper().
cmd_setport()
int cmd_setport (char * args, MsgType msgtype, char * reply)
SETPORT command - set/query comm port attributes re-initialize the microstep drive.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
setport [speed databits stopbits parity]
Sets/Queries the attributes of the open comm port. Also reports if the commport is open or not.
References commandID, and StrUpper().
cmd_moverel()
int cmd_moverel (char * args, MsgType msgtype, char * reply)
moverel command - relative move command +/-value
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
moverel [mechanism val]
mechanism - Mechanism name
val - relative position +/-value
Send relative move MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References commandID, getMechanismID(), positionToShrMem(), sendCommand(), and StrUpper().
cmd_moveabs()
int cmd_moveabs (char * args, MsgType msgtype, char * reply)
moveabs command - absolute command move
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
moveabs [val]
mechanism - Mechanism name
val - relative position +/-value
Send absolute move MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References commandID, getMechanismID(), positionToShrMem(), sendCommand(), and StrUpper().
cmd_hatch()
int cmd_hatch (char * args, MsgType msgtype, char * reply)
hatch command - command the hatch to Open or Close
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
hatch [open|close]
open - Open the MODS hatch or darkslide and let photons enter
close - Close the MODS hatch or darkslide
Description: Opens or closes the instrument dark hatch.
Interactions:
Requires an executive override to open the dark hatch if any of the calibration lamps are turned on.
Send hatch MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References BI_STATE, checkPower(), commandID, getMechanismID(), ierr, mlcBitsBase10(), mlcBusy(), mlcMechanismConfig(), mlcQuery(), mlcReset(), mlcStopMechanism(), mlcTechCmd(), positionToShrMem(), rawCommand(), sendCommand(), and StrUpper().
cmd_calib()
int cmd_calib (char * args, MsgType msgtype, char * reply)
calib command - command the Calibration Tower
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
calib [in|out]
in - Move calibration tower into beam
close - Move calibration tower out of beam
Description:
Inserts the calibration tower into the beam to take calibration data (spectral-line or continuum lamps), or retract the tower and stow it out of the beam.
Interactions:
Hardware and software interlocks with the AGW Stage: the AGW Stage X and Y positions must be HOME before the calibration tower may be moved into the beam. An executive override is required to retract the calibration tower if any of the calibration lamps are still turned on.
Send Calibration Tower MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References checkPower(), commandID, getMechanismID(), ierr, mlcBitsBase10(), mlcBusy(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), positionToShrMem(), rawCommand(), sendCommand(), and StrUpper().
cmd_minsert()
int cmd_minsert (char * args, MsgType msgtype, char * reply)
minsert command - command the Insert Mask mechanism
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
mask [in|out|stow]
in - extract the slit mask from the cassette and deploy it in the focal plane
out - withdraw the slit mask halfway from the focal plane
stow - withdraw the slit mask from the focal plane an stow it in the cassette
Description:
http://www.astronomy.ohio-state.edu/~rgonzale/MODS_ICSCommands.pdf
If in, it extracts the currently selected mask from the cassette and deploys it in the MODS focal plane.
If out, it withdraws the mask from the focal plane and stows it in the mask cassette provided of course that cassette position is unoccupied. Preventing this is one of the duties of the software interlock system.
MASK does not make a mask selection; see SLITMASK to select a mask from the cassette for insertion into the focal plane.
If there is no mask either deployed at the focal plane or stowed in the mask cassette, it returns an error: "No mask available in the cassette to [stow|deploy]".
Interactions: Interlocked with the slit mask cassette mechanism
(hardware & software).
Send a mask MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References checkPower(), commandID, getMaskNumber(), getMechanismID(), ierr, isisStatusMsg(), mlcBitsBase10(), mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), positionToShrMem(), rawCommand(), sendCommand(), and StrUpper().
cmd_mselect()
int cmd_mselect (char * args, MsgType msgtype, char * reply)
mselect command - command the Mask Select mechanism
Parameters
args string with command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
mselect [n|brace|step +/-n|reset|cwlimit|ccwlimit]
n - number of the slit mask to select (1..24) brace - selects the support brace position (sensor test position) step - move +/- number of mask positions cwlimit - go to the ClockWise(CW) limit position ccwlimit - go to the CounterClockWise(CCW) limit position findpos - go to the In Position(IP) bit.
Description:
http://www.astronomy.ohio-state.edu/~rgonzale/MODS_ICSCommands.pdf
Move the slit mask cassette to place the mask in cassette slot n into position for insertion into the MODS focal plane.
If given without arguments, it returns the slit mask cassette slot currently in position, and indicates whether or not a mask is actually loaded in that slot in the cassette along with its ID if known.
SLITMASK does not insert the named slit mask into the focal plane, it only positions the mask cassette mechanism to the requested position preparatory to insertion with the MASK command.
If there is already a slit mask deployed in the focal plane, a request to move the slit mask cassette mechanism will be denied and return an error requesting that the currently deployed mask be retracted first using the "MASK out" command.
Interactions: Interlocked with the slit mask insert/retract mechanism
(hardware & software).
Send a mask MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, checkPower(), commandID, getMaskNumber(), getMechanismID(), ierr, isisStatusMsg(), mlcBitsBase10(), mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), rawCommand(), sendCommand(), sendTwoCommand(), and StrUpper().
cmd_slitmask()
int cmd_slitmask (char * args, MsgType msgtype, char * reply)
slitmask command - command the slit mask for deployment
Parameters
args string with command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
slitmask [n|ID] [in|out]
n - number of the slit mask to select (1..24) ID - select a slitmask by name instead of storage cassette location number in - insert the mask into the science beam out - remove the mask from the science beam (stow in the cassette)
Range: 1..24
Description:
http://www.astronomy.ohio-state.edu/~rgonzale/MODS_ICSCommands.pdf
Move the slit mask cassette to place the mask in cassette slot n into position for insertion into the MODS focal plane.
If given without arguments, it returns the slit mask cassette slot currently in position, and indicates whether or not a mask is actually loaded in that slot in the cassette along with its ID if known.
SLITMASK does not insert the named slit mask into the focal plane, it only positions the mask cassette mechanism to the requested position preparatory to insertion with the MASK command.
If there is already a slit mask deployed in the focal plane, a request to move the slit mask cassette mechanism will be denied and return an error requesting that the currently deployed mask be retracted first using the "MASK out" command.
Interactions: Interlocked with the slit mask insert/retract mechanism
(hardware & software).
Send a mask MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References checkPower(), commandID, getMaskNumber(), getMechanismID(), ierr, isisStatusMsg(), mlcBitsBase10(), mlcBusy(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), positionToShrMem(), rawCommand(), sendCommand(), sendTwoCommand(), and StrUpper().
cmd_agw()
int cmd_agw (char * args, MsgType msgtype, char * reply)
AGW command - Configure the AGW stage.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
agw [xpos ypos fpos]
xpos - X-axis position in integer microns from mechanism home
ypos - Y-axis position in integer microns from mechanism home
fpos - focus position in integer microns from mechanism home
Description:
AGW performs low-level configuration of the AGW stage, combining the operations of AGWX, AGWY, and AGWFS into a single command. If the home keyword is given, it retracts all 3 stage axes to their home (mechanical zero) positions.
Interactions: Interlocked with the Calibration Tower
(hardware & software).
Send AGW Stage commands MicroLYNX controller command via network or serial.
References commandID, getMechanismID(), ierr, mlcBitsBase10(), and StrUpper().
cmd_agwy()
int cmd_agwy (char * args, MsgType msgtype, char * reply)
agwY command - AGW Stage Y-axis position
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
agwy [ypos]
ypos - Y-axis position in integer microns from mechanism home
home - retract the AGW Y-axis stage to its home position.
init - init is Y towards the CW limit switch
Description:
Move the AGW stage to the specified Y-axis position in integer microns. The Y-axis position is measured relative to the axis home sensor, which is fully retracted towards the motor, which moves it as far away as possible from the instrument focal plane.
Interactions: Interlocked with the Calibration Tower
(hardware & software)
Send AGW X MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, commandID, getMechanismID(), ierr, mlcBitsBase10(), and StrUpper().
cmd_agwx()
int cmd_agwx (char * args, MsgType msgtype, char * reply)
agwX command - AGW Stage X-axis position
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
agwx [xpos]
xpos - X-axis position in integer microns from mechanism home
home - retract the AGW X-axis stage to its home position. init - init is X towards the CW limit switch
Description:
Move the AGW stage to the specified X-axis position in integer microns. The X-axis position is measured relative to the axis home sensor, which is fully retracted towards the motor.
Interactions: Interlocked with the Calibration Tower
(hardware & software)
Send AGW X MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, atobase(), commandID, getMechanismID(), ierr, mlcBitsBase10(), and StrUpper().
cmd_agwfoc()
int cmd_agwfoc (char * args, MsgType msgtype, char * reply)
agwfoc command - AGW Stage Focus Position
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
agwfoc [fpos]
fpos - focus position in integer microns from mechanism home
home - retract the AGW focus actuator to its home position.
init - init is Focus towards the CCW limit switch
Description:
Move the AGW stage pickoff mirror focus actuator to the specified position in integer microns. The focus position is measured relative to the mechanism home, which is fully retracted towards the motor. The focus motion is in the same axis and sense as the AGWY mechanism.
Interactions: Interlocked with the Calibration Tower
(hardware & software)
Send AGW Focus MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, commandID, getMechanismID(), ierr, mlcBitsBase10(), and StrUpper().
cmd_agwfilt()
int cmd_agwfilt (char * args, MsgType msgtype, char * reply)
agwfilt command - AGW Guide Camera Filter Wheel
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
agwfilt [n|ID]
n - select AGW filter by position number (1..4)
ID - select AGW filter by name
Description:
Select the filter to put in front of the acquisition and guide CCD camera. Note that the light going into the off-axis wavefront sensor (WFS) camera is unfiltered.
AGW filter names are stored in an external AGW filter table populated via the MODS Engineering Support Interface (MESI).
Interactions: none
Send AGW Filter Wheel MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References commandID, getMechanismID(), ierr, and StrUpper().
cmd_dichroic()
int cmd_dichroic (char * args, MsgType msgtype, char * reply)
dichroic command - command the Dichroic
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
dichroic [n|blue|red|both]
Send Dichroic MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, commandID, getMechanismID(), ierr, mlcBitsBase10(), mlcBusy(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), rawCommand(), sendCommand(), sendTwoCommand(), and StrUpper().
cmd_gprobe()
int cmd_gprobe (char * args, MsgType msgtype, char * reply)
gprobe command - Move AGW guide probe to an absolute X,Y position
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
gprobe [Ygp Xgp|reset]
XGP - guide probe field center X-axis position in millimeters
YGP - guide probe field center Y-axis position in millimeters
home - home the guide probe
Description:
Move the AGW stage pickoff mirror center to the specified absolute (X,Y) position in the MODS science focal plane, including autofocus adjustment for the curved focal plane. Coordinates are given in millimeters from the center of the science field, as described in the MODS AGW Specification document. When the instrument PA is 0deg, +XGP is East, -XGP is West, +YGP is North, and -YGP is South. The origin (XGP,YGP)=(0,0) is the center of the guider camera field of view at the MODS science field center (the optical axis of the focus).
If the home keyword is given, it retracts the guide probe to its home (mechanical zero) position, out of the science beam. This is equivalent to giving the individual commands "AGWX home", "AGWY home", and "AGWFS home".
Both XGP and YGP must be given device coordinates and then executes equivalent AGWX, AGWY, and AGWFS motions.
Interactions: Interlocked with the Calibration Tower
(hardware & software).
Send Guide Probe MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, commandID, getMechanismID(), ierr, mlcBitsBase10(), mods_fatalerrormsg, and StrUpper().
cmd_gpoffset()
int cmd_gpoffset (char * args, MsgType msgtype, char * reply)
gpoffset command - Offset the AGW guide probe deltaX, deltaY
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: GPOFFSET [dXGP dYGP]
deltaXGP - guide probe X-axis offset in mm
deltaYGP - guide probe Y-axis offset in mm
Description:
Offset (increment) the AGW stage pickoff mirror center by the specified relative amount in millimeters. When the instrument PA is 0deg, +deltaXGP is East, -deltaXGP is West, +deltaYGP is North, and -deltaYGP is South.
Both deltaXGP and deltaYGP must be given. If no offset is required along a given axis, 0 must be given as a placeholder.
GPOFFSET does a relative move, whereas GPROBE does an absolute "move to". Like GPROBE, this command is a user-level meta command that transforms guide-probe focal plane coordinates into device coordinates then executes equivalent AGWX, AGWY, and AGWFS motions.
Interactions: Interlocked with the Calibration Tower (hardware & software).
Send Guide Probe Offset MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References commandID, ierr, and StrUpper().
cmd_gpfocus()
int cmd_gpfocus (char * args, MsgType msgtype, char * reply)
gpfocus command - AGW Probe Focus Position
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
gpfocus [foc]
foc - guide probe focus position in millimeters home - retract the AGW focus actuator to its home position.
init - init is Focus towards the CCW limit switch
Description:
Changes the focus of the guide probe to the specified absolute position. For relative focus changes, use the STEP keyword (e.g., GPFOCUS STEP -5). When the guider focus is changed, the Y stage is back-driven in reflex to preserve the absolute guide probe (XGP,YGP) position.
Interactions: Interlocked with the Calibration Tower
(hardware & software)
Send AGW Probe Focus MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, commandID, getMechanismID(), ierr, mlcBitsBase10(), and StrUpper().
cmd_colttf()
int cmd_colttf (char * args, MsgType msgtype, char * reply)
colttf command - Set a collimator mirror tip/tilt/focus actuator
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cCOLTTFx [pos]
c - channel (B or R)
x - actuator ID, x={A,B,C}
pos - linear position measured in microns from device home
Description:
Moves the named collimator mirror tip/tilt/focus (TTF) actuator to the specified position in units of microns from the device home position. Increasing TTF position moves that part of the collimator mirror closer to the slit. There are 3 instances of this mechanism per channel.
If given without arguments, the command returns the current position of that actuator.
To move an actuator + or - relative to the current position, use the STEP keyword.
To set/query all 3 actuators at once, see the BCOLFOC and RCOLFOC commands.
Interactions: none
Send Collimator offsets MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References checkPower(), commandID, getMechanismID(), ierr, LINEAR, mlcBitsBase10(), mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcQuery(), mlcStep(), mlcStopMechanism(), mlcTechCmd(), rawCommand(), and StrUpper().
cmd_colfoc()
int cmd_colfoc (char * args, MsgType msgtype, char * reply)
colttf command - Set the collimator mirror absolute focus position
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cCOLFOC [step] [focval|ttfA ttfB ttfC]
c - channel (B or R)
foc - focus position (piston) of the mirror in microns from device home
ttf# - positions for each of the 3 TTF actuators (#={A.B.C})
Description:
Pistons the named collimator mirror by moving all 3 tip/tilt/focus (TTF) actuators by the same amount. Increasing focus position moves the collimator mirror closer to the slit.
Alternatively, the command can be used to drive the mirror back to its mechanical home position (hence away from the slit), or to move each TTF actuator by a different amount.
The focus motion specified by the single "foc" value maintains the relative positions of the 3 actuators, and is defined as the mean of the current actuator positions: foc = (ttfA+ttfB+ttfC)/3
This ensures that as the focus is changed, the relative alignment of the collimator mirror with the optical axis will stay unchanged.
An alternative is to give 3 numerical arguments for the collimator TTF actuators ttfA, ttfB, and ttfC to set each TTF actuator separately. All 3 must be given. This has the effect of changing the focus (piston) and relative aspects (tip/tilt) simultaneously.
When homing the collimator mirror with the home keyword, all 3 TTF actuators are driven to their mechanical home positions regardless of their relative aspects before homing was requested.
If the requested focus motion would drive any of the actuators out of range, an error is reported and the motion request denied.
If given without arguments, the command returns the current focus position, as well as the corresponding positions of the individual TTF actuators.
To set/query an individual actuator independently while leaving the others unchanged, see the cCOLTTFn commands.
To make incremental +/- changes to the collimator mirror focus, use the STEP keyword
Interactions: none
Send Collimator focus MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands doc. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References checkPower(), commandID, getMechanismID(), ierr, LINEAR, mlcBitsBase10(), mlcQuery(), mlcStep(), mlcStopMechanism(), rawCommand(), and StrUpper().
cmd_grating()
int cmd_grating (char * args, MsgType msgtype, char * reply)
grating command - Select a grating in the grating turret
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cGRATING [n|ID]
c - channel (B or R) n - select grating by number [1..4] ID - select grating by name Range: 1..4 for grating numbers
Description:
Select the grating to put in the collimated beam for the named channel. If given without arguments, it returns the current grating position and its name.
Grating names are stored in an external grating table populated via the MODS Engineering Support Interface (MESI).
If selecting a grating by name, an exact name match (case insensitive) is required. If the grating position also has an associated grating tilt mechanism, it must be tilted separately using the cGRTILTn command, where n corresponds to the grating turret position (1..4), or the tilt incremented (stepped) using cGRSTEPn.
Interactions: none
Send Blue or Red Grating Select to MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands documentation. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References checkPower(), commandID, getMechanismID(), ierr, mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), rawCommand(), sendCommand(), sendTwoCommand(), and StrUpper().
cmd_grtilt()
int cmd_grtilt (char * args, MsgType msgtype, char * reply)
grating command - Tilt grating n to a given absolute tilt
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cGRTILTn [tilt|home]
c - channel (B or R) tilt - amount to tilt grating n, in device units n - grating to tilt (corresponds to position in the turret, 1..4) home - set the grating tilt to the mechanical home position
Description:
Tilts the selected grating to the specified position relative to the mechanism home position. If "home" is given instead of position value, the grating tilt is driven to the mechanical home position.
If given without arguments, it returns the current tilt position.
If the grating at that position has no tilt mechanism (e.g., the imaging flat or double-pass prisms), an error is returned.
The grating tilt can be incremented ("stepped") relative to its current position with a corresponding cGRSTEPn command.
Note that a grating can be tilted even if it is not selected to be in the "in-beam" position by the cGRATING command.
Interactions: none
Send Blue or Red Grating Tilt to MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands documentation. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References commandID, getMechanismID(), ierr, mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), mmcLOGGER(), positionToShrMem(), rawCommand(), sendCommand(), and StrUpper().
cmd_shutter()
int cmd_shutter (char * args, MsgType msgtype, char * reply)
shutter command - Open/Close the camera shutter
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cSHUTTER [open|close]
c - channel (B or R) open - open the named camera shutter close - close the named camera shutter
Description:
Opens or closes the shutter on the named camera. If given without arguments it returns the current shutter status (open or closed) of the named camera.
The shutter will stay open indefinitely after this command, it does not perform a timed shutter cycle (that is done through the detector control system).
Interactions: none
Send Blue or Red Shutter to MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands documentation. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References commandID, getMechanismID(), he_token, ierr, mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), rawCommandOnly(), sendCommand(), and StrUpper().
cmd_camfoc()
int cmd_camfoc (char * args, MsgType msgtype, char * reply)
camfoc command - Focus the camera primary mirror
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cCAMFOC [foc|home|step +/-foc]
c - channel (B or R) foc - focus position of the camera primary mirror in device units home - send the camera primary mirror focus to its mechanical home position
Description:
Sets the named camera primary mirror absolute focus position.
Increasing focus position moves the camera primary mirror closer to the CCD detector.
The home keyword is used to drive the camera primary mirror to the mechanical home position (and away from the CCD).
If given without arguments, it returns the absolute focus position of the named camera primary mirror.
To make incremental +/- changes to the camera primary mirror focus, use STEP.
Interactions: none
Send Blue or Red Focus to MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands documentation. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, checkPower(), commandID, getMechanismID(), ierr, mlcBitsBase10(), mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), positionToShrMem(), rawCommand(), sendTwoCommand(), and StrUpper().
cmd_filter()
int cmd_filter (char * args, MsgType msgtype, char * reply)
filter command - Select a filter on the filter wheel
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: cFILTER [n|ID] [load]
c - channel (B or R) n - select filter by number [1..8] ID - select filter by name Range: 1..8 for filter numbers load - select filter position for loading: Range: 1..8 filter position
Description:
Select the filter to put in front of the CCD in the named camera. If given without arguments, it returns the current filter position and its name.
Filter names are stored in an external filter table populated via the MODS Engineering Support Interface (MESI).
If selecting a filter by name, an exact name match (case insensitive) is required.
Interactions: none
Send Blue or Red Filter Wheel to MicroLYNX controller command via network or serial. MicroLYNX Controller commands given in MODS Mechanism Commands documentation. http://www.astronomy.ohio-state.edu/~rgonzale/MODS_Mechanism_Commands.pdf
References argbuf, commandID, getMechanismID(), ierr, mlcBitsBase10(), mlcBusy(), mlcMechanismConfig(), mlcQuery(), mlcStopMechanism(), mlcTechCmd(), rawCommand(), sendTwoCommand(), and StrUpper().
cmd_lamp()
int cmd_lamp (char * args, MsgType msgtype, char * reply)
lamp command - Operate the calibration lamps
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
LAMP [lamp1 lamp2 ...] [ON|OFF|INFO]
lampN - name(s) of the calibration lamp(s) to operate
ON - turn the selected lamp(s) on
OFF - turn the selected lamp(s) off
INFO - return information about the named lamp(s)
Description:
Select one or more calibration lamps and then either turn them on or off or get information about them. The command arguments consist of a list of one or more lamps to be operated, followed by a keyword giving the operation to be performed. The calibration lamp names are as follows:
Flat1 QTH1 flat field (continuum) lamp 1
Flat2 QTH2 flat field (continuum) lamp 2
Flat3 VFLAT flat field (continuum) lamp 3
Ne Neon penray lamp
Xe Xenon penray lamp
Hg Mercury(Argon) penray lamp
Ar Argon penray lamp
Kr Krypton penray lamp
The operations that can be performed on these lamps are as follows:
ON Turn the named lamp(s) ON. 1 or more lamps must be named.
OFF Turn the named lamp(s) OFF. If no lamps named, turns off all MODS.lamps.
INFO Return information about the named lamps(s)
If the INFO operation is requested, it returns the following information vector about named lamp "LampID":
LampID=(State,TimeOn,Age,Cycles)
where:
State current power state of the lamp (On or Off)
TimeOn elapsed time in seconds the lamp has been lit if On, or 0 if Off
Age total time the lamp has been powered on in since installation (seconds)
Cycles number of times the lamp has been power cycled since installation
Both OFF and INFO have implicit "all" options if no lamp names are given on the command line, thus
LAMP OFF turns off all lamps
LAMP INFO returns information about all lamps
Finally, if LAMP is given with no arguments, it reports the names of all lamps that are currently on.
Interactions:
An executive override is required to turn on any lamp if the calibration tower is out of the beam and/or the dark hatch is open. However, lamps may be turned off and their info queried at any time without regard to the dark hatch or calibration tower status.
References commandID, getWagoID(), ierr, llbID, LLBONOFF, StrUpper(), VFLATPSET, and wagoSetGet().
Referenced by cmd_pstatus().
cmd_vislaser()
int cmd_vislaser (char * args, MsgType msgtype, char * reply)
vislaser command - Operate the IMCS Visible-light Alignment Laser
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
VISLASER [pon|poff] [enable|disable] [power [lev]] [status|info]
  pon|poff - Turn the visible laser unit's main power on or off
enable|disable - Enable/disable the laser output (beam "on/off") power [lev] - Set/query the laser power output level status - Query the laser's current operating status info - Query laser system information
Description:
Sets or queries the current state of the visible-light red laser used for optical alignment. This is an engineering laser that is co-aligned with the Infrared reference laser used by the Image Motion Compensation System (IMCS), but otherwise it is not used during normal observing operations.
As with the IR laser unit, there are two power settings:
Main power to the laser controller electronics
Power to the laser head, which enables light output These power functions are provided by this command as follows
VISLASER [pon|poff]
Turns on the main power to the visible laser control unit. This powers up the main laser control electronics but does not turn on the laser itself (no light out the fiber).
VISLASER [enable|disable]
Enables or disables laser light output to the fiber. To turn output off without powering down the laser controller, "VISLASER disable" is used.
Additional command options are used to change the light output power, change the temperature controller settings, and request status information of the laser system proper.
These functions are as follows:
VISLASER power [lev]
Sets the current laser output power to "lev", or returns the current output power setting if given without the lev argument. If laser output is currently disabled, it will set the power level that will be used when laser output is next enabled.
VISLASER status
Returns a status string with the current status of the laser, giving the power state of the controller, a flag that indicates if the laser is enabled or disabled, and the power level.
Examples:
Command> VISLASER
Response> DONE: VISLASER=ON VISBEAM=ENABLED VISPSET=100 VISPOUT=100
This command just reports the current status of the Visible Laser system.
See the keyword listing for the meaning of each parameter above.
Command> VISLASER disable
Response> DONE: VISLASER=ON VISBEAM=DISABLED ...
This disabled the visible laser output, but keeps the main power on and the various controller settings as is.
Interactions:
The visible-light laser system is an engineering-only facility, and in normal operation the unit should be always powered off and disabled.
No observer-level commands should be provided for VISLASER control.
References commandID, findPoly(), getWagoID(), ierr, llbID, LLBONOFF, StrUpper(), VISPOUTWAGO, VISPSETWAGO, and wagoSetGet().
cmd_irlaser()
int cmd_irlaser (char * args, MsgType msgtype, char * reply)
irlaser command - Operate the IMCS Infrared Reference Laser
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
IRLASER [on|off[pwr]] [enable|disable] [power [P]] [temp] [status|info]
  pon|poff - Turn the laser unit's main power on or off, with optional
enable|disable - Enable/disable the laser output (beam "on/off") power [P] - Set/query the laser power output level(mW); P=0..2mW temp - Report the laser-head set-point and operating temperature(C) status - Query the laser's current operating status info - Query laser system information
Description:
Sets or queries the current state of the infrared InGaAs laser that provides the reference for the Image Motion Compensation System(IMCS).
Interactions:
References commandID, findPoly(), getWagoID(), ierr, IRPOUTWAGO, IRPSETWAGO, IRTOUTWAGO, IRTSETWAGO, llbID, LLBONOFF, StrUpper(), and wagoSetGet().
cmd_abort()
int cmd_abort (char * args, MsgType msgtype, char * reply)
ABORT command - abort all one or more mechanisms.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
abort [who|all]
Immediately stops one(who) or all mechanism motion and holds the current position (?sets the brakes?).
Lock Behavior:
ABORT - hit the panic button and override.
References commandID, getMechanismID(), ierr, mlcStopMechanism(), and StrUpper().
cmd_power65()
int cmd_power65 (char * args, MsgType msgtype, char * reply)
POWER65 command - Turn on/off 65 VDC power supply.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
power65 [ON|OFF|READ]
Turn off the Power Supply gracefully.
Lock Behavior:
References argbuf, commandID, getWagoID(), ieb1ID, ierr, StrUpper(), and wagoSetGet().
cmd_ieb()
int cmd_ieb (char * args, MsgType msgtype, char * reply)
ieb command - IEB interface
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
ieb [status|power|temp|mlc[1..16]] [n] [on|off]
status = Read the current status
power = IEB n power ON full or OFF standby
temp = Read the current IEB internal temperature
mlc = MicroLynx Controller
n = IEB ID or MicroLynx Controll ID
on = Turn ON the power
off = Turn OFF the power
Description:
IEB Interface
Lock Behavior:
References argbuf, commandID, getMechanismID(), ierr, StrUpper(), wagoRW(), and wagoSetGet().
cmd_imcs()
int cmd_imcs (char * args, MsgType msgtype, char * reply)
IMCS command - report quadcells Open/Close loop.
Parameters
args string with the command-line arguments
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
return #CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage: IMCS
Description:
References argbuf, commandID, getMechanismID(), hebCommand(), ierr, and StrUpper().
cmd_loadplc()
int cmd_loadplc (char * args, MsgType msgtype, char * reply)
LOADPLC command - load MicroLYNX controller with Ladder code.
Parameters
msgtype message type if the command was sent as an IMPv2 message
reply string to contain the command return reply
Returns
#CMD_OK on success, #CMD_ERR if errors occurred, reply contains an error message.
Usage:
loadplc
Send file to MicroLYNX controller via network or serial.
KeyCommand()
void KeyCommand (char * line, char reply[])
Process a command from the client's console keyboard.
Parameters
line string with the keyboard command
reply string to contain reply
See also
SocketCommand()
References client, commandID, HandleInt(), and who_srcID.
Referenced by agwProbe(), agwRestore(), Calib(), cmd_istatus(), cmd_misc(), Hatch(), mlcStow(), and thread_init_func().
SocketCommand()
void SocketCommand (char * buf)
Process a message/command from a remote ISIS server/client application.
Parameters
buf string with the IMPv2 message received from the remote application
This function parses a message received from a remote ISIS server or client application, and interprets the message. All EXEC: and implicit REQ: type messages are passed to the corresponding cmd_xxx() action functions for handling, while the remaining informational messages are simply echoed to the console screen.
More sophisticated handlers might pass such messages on to parsers/handlers of their own if the inputs were actually used for something other than "visual" information for the user of this application.
All messages received from an ISIS node are assumed to be in the proper IMPv2 messaging syntax.
Note that EXEC: is new to IMPv2. It allows remote nodes to transmit protected "executive" commands to clients, giving them access to commands that would otherwise only be available on the console keyboard (e.g., the "quit" command). Thus a remote EXEC: command means "act as if this was typed at the keyboard". It is the responsibility of the remote application to make sure that EXEC: is used with care, as you could do something stupid (though your client application should not allow actions that would be physically unsafe to personnel or equipment).
See also
KeyCommand()
References buf, client, commandID, mmcLOGGER(), StrUpper(), and who_srcID.
Referenced by thread_init_func().
findPoly()
float findPoly (float x, float * a, int n)
Referenced by cmd_irlaser(), and cmd_vislaser().
dfindPoly()
double dfindPoly (double x, double * a, int n)
Variable Documentation
argbuf
char argbuf[MAXPGMLINE]
Referenced by agwProbe(), agwRestore(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_camfoc(), cmd_close(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gprobe(), cmd_help(), cmd_ieb(), cmd_imcs(), cmd_misc(), cmd_mselect(), cmd_mstatus(), cmd_open(), cmd_power65(), LoadConfig(), mlcPANIC(), rawCommand(), sendCommand(), and wagoRW().
commandID
int commandID
Referenced by cmd_abort(), cmd_agw(), cmd_agwfilt(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_calib(), cmd_camfoc(), cmd_close(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gpoffset(), cmd_gprobe(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_ieb(), cmd_imcs(), cmd_info(), cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_minsert(), cmd_misc(), cmd_moveabs(), cmd_moverel(), cmd_mselect(), cmd_mstatus(), cmd_open(), cmd_ports(), cmd_power65(), cmd_pstatus(), cmd_setport(), cmd_shutter(), cmd_slitmask(), cmd_version(), cmd_vislaser(), KeyCommand(), and SocketCommand().
mods_fatalerrormsg
char* mods_fatalerrormsg[] extern
Referenced by cmd_gprobe().
who_srcID
char who_srcID[MAXPGMLINE]
Referenced by isisStatusMsg(), KeyCommand(), and SocketCommand().
llbID
int llbID
Referenced by cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_misc(), cmd_vislaser(), and main().
utilID
int utilID
Referenced by cmd_istatus(), cmd_misc(), and main().
ieb1ID
int ieb1ID
Referenced by cmd_power65(), and main().
ieb2ID
int ieb2ID
Referenced by main().
ierr
int ierr
Referenced by agwProbe(), agwRestore(), bcolfoc_to(), Calib(), checkPower(), cmd_abort(), cmd_agw(), cmd_agwfilt(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_calib(), cmd_camfoc(), cmd_close(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gpoffset(), cmd_gprobe(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_ieb(), cmd_imcs(), cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_minsert(), cmd_misc(), cmd_mselect(), cmd_mstatus(), cmd_open(), cmd_power65(), cmd_pstatus(), cmd_shutter(), cmd_slitmask(), cmd_version(), cmd_vislaser(), getMaskNumber(), Hatch(), hebCommand(), isisStatusMsg(), main(), mlcBitsBase10(), mlcBusy(), mlcCheckBits(), mlcMechanismConfig(), mlcPANIC(), mlcQuery(), mlcReset(), mlcStep(), mlcStopMechanism(), mlcStow(), mlcTechCmd(), openCommand(), rawCommand(), rawCommandOnly(), rcolfoc_to(), sendCommand(), sendMultiCommand(), sendTwoCommand(), thread_init_func(), and wagoRW().
he_token
int he_token =1
Referenced by cmd_shutter().
inbuf
char inbuf[MAXPGMLINE]
Referenced by LoadConfig().
pgmFP
FILE* pgmFP