mmcService - Interactive MODS Mechanism Control System: mlc.c File Reference
mlc.c File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstring>
#include <vector>
#include <cstdlib>
#include "ISLSocket.h"
#include "timer.h"
#include "islapi.h"
Macros
#define BUFFSIZE 512
#define IO20 "PRINT IO 20\r"
Functions
int reusePort (int)
int checkForError (int, char *)
char * makeUpper (char str2[])
Return uppercase string.
char * makeLower (char str2[])
Return lowercase string.
void StrUpper (char *str)
Convert all characters in a string to uppercase.
int openCommand (int i, char dummy[])
Open a command port to a mechanism.
int closeCommand (int i, char dummy[])
Close a command port to a mechanism.
double positionToShrMem (int i, char dummy[])
Send position to shared memory and return position to caller.
int sendCommand (int i, char cmd[], char dummy[])
Send a command to a mechanism.
int sendMultiCommand (int i, char cmdlist[][80], int cnt, char dumlist[][512])
Send Multiple Commands to a mechanism.
int sendTwoCommand (int i, char cmd[], char cmd2[], char dummy[])
Send a command to a mechanism.
int rawCommand (int i, char cmd[], char dummy[])
Send a raw microLynx command to a mechanism.
int rawCommandOnly (int i, char cmd[])
Send a raw microLynx command to a mechanism with no reply.
int hebCommand (int i, char cmd[], char dummy[])
Send a raw microLynx command to a mechanism.
int mlcCheckBits (int i, char dummy[])
Check mechanism limit bits.
int mlcQuery (int i, long timeout, char dummy[])
Query the device with a short time out.
int mlcStopMechanism (int i, char dummy[])
Stop the current operation.
int getMaskNumber (int i, char dummy[])
Get the mask ID from the mechanism IO 30 bits.
int mlcActivePorts (char dummy[])
List active Comtrol to MicroLynx ports.
int mlcWhoAmI (int device, char mechanism_name[], char dummy[])
Compare names.
int getMechanismID (char mechanism_name[], char dummy[])
Get the mechanism ID from Shared Memory.
int getWagoID (char wagoid_name[], char dummy[])
Get the WAGO ID from Shared Memory.
int checkPower (int device, char dummy[])
Check the mechanism power.
int mlcBusy (int device, char dummy[])
Check to see if the mechanism is busy.
int mlcTechCmd (int device, char args[], char who[], char dummy[])
Check the mechanism power.
int mlcClear (int i, char dummy[])
Clear the NVM on the MicroLynx Controller.
int mlcSendGet (int mlcUnit, char cmd[], char dummy[])
Query or Send a command to a mechanism.
int digit (char c)
int atobase (char *s, int radix)
hex, octal, hex, octal, hex what the heck is this a base convert, what kind of god would allow this!!!!
int isisStatusMsg (char dummy[])
Status message for request Agent.
int mlcBitsBase10 (int i, char cmd[], char dummy[])
Check mechanism IO bits.
int mlcLimitBits (int i, char dummy[])
Check mechanism IO bits.
int mlcReset (int i, char who[], int what, char how[], char dummy[])
Seek the last known mechanism position.
int mlcStep (int i, char who[], int what, float val, char dummy[])
Seek the last known mechanism position.
int wagoRW (int iebID, char who[], int what, int value, char dummy[])
Last known mechanism position, lamps, and lasers.
int mlcMechanismConfig (int device, char who[], char dummy[])
Get mechanism configuration information.
int mlcStow (char who[], char dummy[])
stow mechanism(s)
int mlcPANIC (int device, char who[], char dummy[])
panic Turns off all Power to MODS1 and/or MODS2. If this command is
int agwRestore (int obscal, char who_selected[], char dummy1[])
agwRestore AGw guide probe
int Hatch (int obscal, char who_selected[], char errorMsg[], char dummy1[])
Open the HATCH or Close HATCH.
int Calib (int obscal, char who_selected[], char errorMsg[], char dummy1[])
Retract or Insert the Calibration Tower.
int agwProbe (int obscal, char who_selected[], char errorMsg[], char dummy1[])
Retract or Move the AGw guide probe into position.
Variables
const int RCVBUFSIZE = 512
Macro Definition Documentation
BUFFSIZE
#define BUFFSIZE 512
IO20
#define IO20 "PRINT IO 20\r"
Function Documentation
reusePort()
int reusePort (int)
checkForError()
int checkForError (int error_number, char * reply)
Referenced by rawCommand(), and sendCommand().
makeUpper()
char* makeUpper (char str2[])
Return uppercase string.
Parameters
str2 string remains unchanged.
str returned as uppercase string,
Helper utility will return requested string in uppercase, and leave the requested string unchanged.
Referenced by checkPower(), closeCommand(), cmd_help(), getMechanismID(), getWagoID(), hebCommand(), mlcBusy(), mlcCheckBits(), mlcLimitBits(), mlcQuery(), mlcReset(), mlcStopMechanism(), openCommand(), positionToShrMem(), rawCommand(), rawCommandOnly(), sendCommand(), sendMultiCommand(), sendTwoCommand(), and wagoRW().
makeLower()
char* makeLower (char str2[])
Return lowercase string.
Parameters
str2 string remains unchanged.
str returned as lowercase string,
Helper utility will return requested string in lowercase, and leave the requested string unchanged.
StrUpper()
void StrUpper (char * str)
Convert all characters in a string to uppercase.
Parameters
str String to be converted to uppercase. Changed by this function.
Helper utility to convert all characters in a string to uppercase. All commands are required to be in uppercase.
openCommand()
int openCommand (int i, char dummy[])
Open a command port to a mechanism.
Parameters
i - port of mechanism
dummy string to contain reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Opens a command port to the named MicroLYNX controller.
References ierr, and makeUpper().
closeCommand()
int closeCommand (int i, char dummy[])
Close a command port to a mechanism.
Parameters
i - port of mechanism
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Close a command port to the named MicroLYNX controller.
References makeUpper().
positionToShrMem()
double positionToShrMem (int i, char dummy[])
Send position to shared memory and return position to caller.
Parameters
i index of the mechanism
dummy reply
Returns
position of the mechanism
Sends the current position of the indicated mechanism to the correct address in device shared memory, and return the same value to the caller.
References makeUpper(), and rmcrlf().
Referenced by cmd_calib(), cmd_camfoc(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_moveabs(), cmd_moverel(), cmd_slitmask(), mlcReset(), and mlcStep().
sendCommand()
int sendCommand (int i, char cmd[], char dummy[])
Send a command to a mechanism.
Parameters
i - index of mechanism
cmd - command string
dummy string to contain reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends a command to the named MicroLYNX controller.
References argbuf, checkForError(), ierr, makeUpper(), and rmcrlf().
Referenced by cmd_calib(), cmd_dichroic(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_moveabs(), cmd_moverel(), cmd_mselect(), cmd_shutter(), cmd_slitmask(), getMaskNumber(), mlcReset(), and mlcStep().
sendMultiCommand()
int sendMultiCommand (int i, char cmdlist[][80], int cnt, char dumlist[][512])
Send Multiple Commands to a mechanism.
Parameters
i - index of mechanism
cmd[] - command list
cnt - number of commands sent
dummy - string to contain reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends Multiple Command to the named MicroLYNX controller.
EXAMPLE for MODS: if you should ever need it. if(!strcasecmp(argbuf,"LIST")) { // ask for help char listdum[5][512]; char listcmds[5][80]; sprintf(&listcmds[0][0],"PRINT POS"); sprintf(&listcmds[1][0],"PRINT ACCL"); sprintf(&listcmds[2][0],"PRINT VM"); sprintf(&listcmds[3][0],"PRINT TARGNUM"); sprintf(&listcmds[4][0],"PRINT DICHNUM"); ierr = sendMultiCommand(device,listcmds,5,listdum); sprintf(reply,"%s %s=%s",who_selected,who_selected,listdum[0]); for(int i=1;i<5;i++) sprintf(reply,"%s\n%s %s=%s",reply,who_selected,who_selected,listdum[i]);
if(ierr!=0) return CMD_ERR;
rawCommand(device,"PRINT POS",dummy); shm_addr->MODS.pos[device]=atof(dummy);
References ierr, makeUpper(), and rmcrlf().
sendTwoCommand()
int sendTwoCommand (int i, char cmd[], char cmd2[], char dummy[])
Send a command to a mechanism.
Parameters
i - index of mechanism
cmd - 1st command string
cmd2 - 2nd command string
dummy string to contain reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends a command to the named MicroLYNX controller.
References ierr, makeUpper(), and rmcrlf().
Referenced by cmd_camfoc(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_mselect(), cmd_slitmask(), and mlcStep().
rawCommand()
int rawCommand (int i, char cmd[], char dummy[])
Send a raw microLynx command to a mechanism.
Parameters
i - index of mechanism
cmd - command string
dummy string to contain reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends a raw microLynx command to the named MicroLYNX controller.
References argbuf, checkForError(), ierr, makeUpper(), and rmcrlf().
Referenced by cmd_calib(), cmd_camfoc(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_mselect(), cmd_mstatus(), cmd_slitmask(), mlcBitsBase10(), mlcStep(), mlcTechCmd(), and thread_init_func().
rawCommandOnly()
int rawCommandOnly (int i, char cmd[])
Send a raw microLynx command to a mechanism with no reply.
Parameters
i - index of mechanism
cmd - command string
return - 0=successful or 1=failed
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends a raw microLynx command with NO reply required
References ierr, and makeUpper().
Referenced by cmd_shutter().
hebCommand()
int hebCommand (int i, char cmd[], char dummy[])
Send a raw microLynx command to a mechanism.
Parameters
i - index of mechanism
cmd - command string
dummy string to contain reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends a raw microLynx command to the named MicroLYNX controller.
References ierr, makeUpper(), and rmcrlf().
Referenced by cmd_imcs().
mlcCheckBits()
int mlcCheckBits (int i, char dummy[])
Check mechanism limit bits.
Parameters
i index of the mechanism
dummy string to contain reply
Returns
The value of the limit bits
Queries the named mechanism and returns the current set of limit bits.
  Bit 26 is the break
  Bits 25 - 23 status
  Bit 22 CCW bit
  Bit 21 CW bit
References ierr, IO20, and makeUpper().
Referenced by cmd_camfoc(), cmd_colttf(), cmd_grating(), cmd_grtilt(), cmd_minsert(), and cmd_mselect().
mlcQuery()
int mlcQuery (int i, long timeout, char dummy[])
Query the device with a short time out.
Parameters
i index of the mechanism
timeout timeout is in sec's
dummy return time out message if timed out
Returns
The value of success for now (0)
Query the named mechanism
References ierr, and makeUpper().
Referenced by cmd_calib(), cmd_camfoc(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_mselect(), cmd_mstatus(), cmd_shutter(), and cmd_slitmask().
mlcStopMechanism()
int mlcStopMechanism (int i, char dummy[])
Stop the current operation.
Parameters
i index of the mechanism
Returns
The value of success for now (0)
Stops the named mechanism current operation and returns
References ierr, and makeUpper().
Referenced by cmd_abort(), cmd_calib(), cmd_camfoc(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_mselect(), cmd_shutter(), and cmd_slitmask().
getMaskNumber()
int getMaskNumber (int i, char dummy[])
Get the mask ID from the mechanism IO 30 bits.
Parameters
i index of the mechanism
dummy reply
Returns
Mask Number or error
Interogates mechanism IO 30 bitmask for Mask Number
  Bit 36-31
References ierr, and sendCommand().
Referenced by cmd_minsert(), cmd_mselect(), and cmd_slitmask().
mlcActivePorts()
int mlcActivePorts (char dummy[])
List active Comtrol to MicroLynx ports.
Parameters
reply reply message
Returns
0 or error
List all Comtrol to MicroLynx Ports.
mlcWhoAmI()
int mlcWhoAmI (int device, char mechanism_name[], char dummy[])
Compare names.
Parameters
request request mechanism name
mlcname microLynx name
Returns
value 1=error, 0=ok
Compare requested name with microLynx name. Give an error if names do not match.
References rmcrlf().
getMechanismID()
int getMechanismID (char mechanism_name[], char dummy[])
Get the mechanism ID from Shared Memory.
Parameters
dummy mechanism
reply reply message
Returns
mechanismID or error
Get Mechanism ID
References makeUpper().
Referenced by agwProbe(), agwRestore(), Calib(), Hatch(), and mlcStow().
getWagoID()
int getWagoID (char wagoid_name[], char dummy[])
Get the WAGO ID from Shared Memory.
Parameters
dummy wago id
reply reply message
Returns
wagoID or error
Get WAGO ID
References makeUpper().
Referenced by cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_misc(), cmd_power65(), cmd_vislaser(), and main().
checkPower()
int checkPower (int device, char dummy[])
Check the mechanism power.
Parameters
device mechanism id
who mechanism name
Returns
power 1=recycled, 0=ok or error
check mechanism power
References ierr, makeUpper(), and rmcrlf().
Referenced by cmd_calib(), cmd_camfoc(), cmd_colfoc(), cmd_colttf(), cmd_grating(), cmd_hatch(), cmd_minsert(), cmd_mselect(), and cmd_slitmask().
mlcBusy()
int mlcBusy (int device, char dummy[])
Check to see if the mechanism is busy.
Parameters
device mechanism id
who mechanism name
Returns
value 1=error, 0=ok
check if mechanism busy
References ierr, and makeUpper().
Referenced by cmd_calib(), cmd_camfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_mselect(), and cmd_slitmask().
mlcTechCmd()
int mlcTechCmd (int device, char args[], char who[], char dummy[])
Check the mechanism power.
Parameters
mlccmd command sent to MicroLynx controller
who mechanism name
dummy return string informantion
Returns
power 1=recycled, 0=ok or error
check mechanism power
References ierr, and rawCommand().
Referenced by cmd_calib(), cmd_camfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_mselect(), cmd_shutter(), and cmd_slitmask().
mlcClear()
int mlcClear (int i, char dummy[])
Clear the NVM on the MicroLynx Controller.
Parameters
i - index of mechanism
dummy - confirm
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Clear MicroLynx Controller NV Memory
mlcSendGet()
int mlcSendGet (int mlcUnit, char cmd[], char dummy[])
Query or Send a command to a mechanism.
Parameters
who - mechanism name
mlcCmdStr - command string
dummy string reply
Returns
Returns CMD_OK on success, CMD_ERR on errors.
Sends a command to the named MicroLYNX controller.
References RCVBUFSIZE, and rmcrlf().
digit()
int digit (char c)
Parameters
c - char to convert
Referenced by atobase().
atobase()
int atobase (char * s, int radix)
hex, octal, hex, octal, hex what the heck is this a base convert, what kind of god would allow this!!!!
Parameters
s - string to convert
radix - base to convert to 2,10,16..etc
Returns
Returns convertion.
Sends a command to the named MicroLYNX controller.
References digit().
Referenced by cmd_agwx(), and mlcBitsBase10().
isisStatusMsg()
int isisStatusMsg (char dummy[])
Status message for request Agent.
Parameters
dummy message string
Returns
The value of -1 is error
Sends status information
References client, ierr, and who_srcID.
Referenced by agwProbe(), agwRestore(), Calib(), cmd_minsert(), cmd_misc(), cmd_mselect(), cmd_slitmask(), Hatch(), main(), and thread_init_func().
mlcBitsBase10()
int mlcBitsBase10 (int i, char cmd[], char dummy[])
Check mechanism IO bits.
Parameters
i index of the mechanism
cmd IO bit string to convert
dummy string to contain reply if error
Returns
The value of the bits in base 10
Queries the named mechanism for bit value
  Bits 1 - 6 IO 20, and IO 30
References atobase(), ierr, and rawCommand().
Referenced by cmd_agw(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_calib(), cmd_camfoc(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gprobe(), cmd_hatch(), cmd_minsert(), cmd_misc(), cmd_mselect(), cmd_slitmask(), and mlcLimitBits().
mlcLimitBits()
int mlcLimitBits (int i, char dummy[])
Check mechanism IO bits.
Parameters
i index of the mechanism
who What mechanism
dummy string to contain reply if error
Returns
0=ok, -1=error
Queries the named mechanism for bit value
  Bits IO 21(CW), and IO 22(CCW)
References makeUpper(), and mlcBitsBase10().
mlcReset()
int mlcReset (int i, char who[], int what, char how[], char dummy[])
Seek the last known mechanism position.
Parameters
i index of the mechanism
who mechanism ID name
what Bi-State=0, Linear=1, Indexed=2
how command initializing or homing
dummy string contains reply
Returns
0=ok, -1=error
Instructs the mechanism to seek its last known safe(usually home) position, reset basic mechanism parameters, and clear fault condition flags
Mechanisms:
Parameters
1.) Bi-State - CW IO 21 or home position
(rare cases CCW IO 22 is home)
2.) Linear - Declared safe in configuration file
loaded into Shared Memory
3.) Index - IO 20 or IO 30 bits for last position
References ierr, makeUpper(), positionToShrMem(), and sendCommand().
Referenced by cmd_hatch().
mlcStep()
int mlcStep (int i, char who[], int what, float val, char dummy[])
Seek the last known mechanism position.
Parameters
i index of the mechanism
who mechanism ID name
what Linear=1, Indexed=2
val +/- relative move in revs
dummy string that contains reply
Returns
0=ok, -1=error
Instructs the mechanism to move +/-n position relative to current position, Indexed mechanisms move full positions, linear move that many units (n=rev, 1rev=200steps)
Mechanisms:
Parameters
1.) Bi-State - +/- Relative move in units
2.) Linear - +/- Relative move in units
3.) Index - move in indexed units
References ierr, positionToShrMem(), rawCommand(), sendCommand(), and sendTwoCommand().
Referenced by cmd_colfoc(), and cmd_colttf().
wagoRW()
int wagoRW (int iebID, char who[], int what, int value, char dummy[])
Last known mechanism position, lamps, and lasers.
Parameters
iebID request IEB 1 or 2
who request from who
what Set or Query (1 or 0)
value a command or an item
dummy string that contains reply
Returns
0=ok, -1=error
Mechanisms, Lamps, and Lasers status
References argbuf, ierr, makeUpper(), and wagoSetGet().
Referenced by cmd_ieb(), and cmd_pstatus().
mlcMechanismConfig()
int mlcMechanismConfig (int device, char who[], char dummy[])
Get mechanism configuration information.
Parameters
device address of the mechanism
who Name of mechanism
dummy string contains reply
Queries the named mechanisms configuration information
References ierr.
Referenced by cmd_calib(), cmd_camfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_minsert(), cmd_mselect(), and cmd_shutter().
mlcStow()
int mlcStow (char who[], char dummy[])
stow mechanism(s)
Parameters
who Name of mechanism or all
dummy string contains reply
Stows on or all MODS mechanisms
References getMechanismID(), ierr, and KeyCommand().
mlcPANIC()
int mlcPANIC (int device, char who[], char dummy[])
panic Turns off all Power to MODS1 and/or MODS2. If this command is
used it means that something very serious has occurred.
Parameters
who Name of MODSx (x=1..2)
dummy string contains reply
PANIC!
References argbuf, ierr, and wagoSetGet().
agwRestore()
int agwRestore (int obscal, char who_selected[], char dummy1[])
agwRestore AGw guide probe
Usage: agwRestore(obscal, who_selected, dummy1)
obscal = Not used here. dummy1 = Return message who_selected = who called me return 0=OK 0<Error Error means that an error was detected;
Moves the AGw guide probe to the previously saved position,
References argbuf, getMechanismID(), ierr, isisStatusMsg(), and KeyCommand().
Referenced by cmd_misc().
Hatch()
int Hatch (int obscal, char who_selected[], char errorMsg[], char dummy1[])
Open the HATCH or Close HATCH.
Usage: Hatch(obscal, who_selected[], errorMsg[], dummy1[])
obscal = (1=CLOSE 0=OPEN) who_selected = who called me errorMsg = For printing to isisStatus() dummy1 = Return message return = 0=OK, >0=Error
Open or close the hatch
References getMechanismID(), ierr, isisStatusMsg(), and KeyCommand().
Referenced by cmd_misc().
Calib()
int Calib (int obscal, char who_selected[], char errorMsg[], char dummy1[])
Retract or Insert the Calibration Tower.
Usage: Calib(obscal, who_selected[], errorMsg[], dummy1[])
obscal = (1=CLOSE 0=OPEN) who_selected = who called me errorMsg = For printing to isisStatus() dummy1 = Return message return = 0=OK, >0=Error
Retract or Insert the Calibration Tower
References getMechanismID(), ierr, isisStatusMsg(), and KeyCommand().
Referenced by cmd_misc().
agwProbe()
int agwProbe (int obscal, char who_selected[], char errorMsg[], char dummy1[])
Retract or Move the AGw guide probe into position.
Usage: agwProbe(obscal, who_selected[], errorMsg[], dummy1[])
obscal = not used who_selected = who called me errorMsg = For printing to isisStatus() dummy1 = Return message return = 0=OK, >0=Error
Retract or Insert the Calibration Tower
References argbuf, getMechanismID(), ierr, isisStatusMsg(), and KeyCommand().
Referenced by cmd_misc().
Variable Documentation
RCVBUFSIZE
const int RCVBUFSIZE = 512
Referenced by mlcSendGet().