mmcService - Interactive MODS Mechanism Control System: mlcClient.cpp File Reference
mlcClient.cpp File Reference
#include "../include/ISLSocket.h"
#include <iostream>
#include <cstdlib>
#include <stdio.h>
Functions
int rmcrlf (char s[], char s1[])
Remove CRLFs and replace them with blanks.
int main (int argc, char *argv[])
Variables
const int RCVBUFSIZE = 8192
Function Documentation
rmcrlf()
int rmcrlf (char s[], char s1[])
Remove CRLFs and replace them with blanks.
Parameters
s String to be returned s1 String to be operated on
Helper utility to change CRLF to blanks in the return string
Referenced by checkPower(), hebCommand(), mlcSendGet(), mlcWhoAmI(), positionToShrMem(), rawCommand(), sendCommand(), sendMultiCommand(), and sendTwoCommand().
main()
int main (int argc, char * argv[])
References RCVBUFSIZE.
Variable Documentation
RCVBUFSIZE
const int RCVBUFSIZE = 8192
Referenced by main().