mmcService - Interactive MODS Mechanism Control System: mlcRecover.cpp File Reference
mlcRecover.cpp File Reference
mlcRecover - Recovers all lost data due to a reboot.
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <vector>
#include <sys/sendfile.h>
#include "instrutils.h"
#include "isl_funcs.h"
#include "isl_types.h"
#include "params.h"
#include "islcommon.h"
#include "isl_shmaddr.h"
Macros
#define MAX_TABLINES 80
maximum number of lines to read from a mechanism table
Functions
void StrUpper (char *str)
Convert all characters in a string to uppercase.
char * getDateTime (void)
Return the UTC date and time to microsecond precision as a system timestamp.
int main (int argc, char *argv[])
Detailed Description
mlcRecover - Recovers all lost data due to a reboot.
Author
Staff, OSU Astronomy Dept. (rgonz.nosp@m.ale@.nosp@m.astro.nosp@m.nomy.nosp@m..ohio.nosp@m.-sta.nosp@m.te.ed.nosp@m.u)
Date
2009 Mar 12 (rdg)
Usage: Unix style.
mlcRecover();
Shared Memory recover function, recovers the MicroLynx Controller state, agwFilter names, camera filter names, and anything else we can think of Information is place computers MODS shared memory segments.
NOTE: These files are kept in /home2/mods/data shrmem.tab, agwfilters.tab, camfilters.tab misc.tab
2025 June 20 - AlmaLinux 9 port [rwp/osu]
Macro Definition Documentation
MAX_TABLINES
#define MAX_TABLINES 80
maximum number of lines to read from a mechanism table
Function Documentation
StrUpper()
void StrUpper (char * str)
Convert all characters in a string to uppercase.
Parameters
str String to be converted to uppercase. Changed by this function.
Helper utility to convert all characters in a string to uppercase. All commands are required to be in uppercase.
Referenced by cmd_abort(), cmd_agw(), cmd_agwfilt(), cmd_agwfoc(), cmd_agwx(), cmd_agwy(), cmd_calib(), cmd_camfoc(), cmd_close(), cmd_colfoc(), cmd_colttf(), cmd_dichroic(), cmd_filter(), cmd_gpfocus(), cmd_gpoffset(), cmd_gprobe(), cmd_grating(), cmd_grtilt(), cmd_hatch(), cmd_help(), cmd_ieb(), cmd_imcs(), cmd_info(), cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_minsert(), cmd_misc(), cmd_moveabs(), cmd_moverel(), cmd_mselect(), cmd_mstatus(), cmd_open(), cmd_ports(), cmd_power65(), cmd_pstatus(), cmd_setport(), cmd_shutter(), cmd_slitmask(), cmd_version(), cmd_vislaser(), main(), and SocketCommand().
getDateTime()
char* getDateTime (void)
Return the UTC date and time to microsecond precision as a system timestamp.
Return the UTC date/time as an ISO 8601 coded string.
Reads the system's UTC time clock and returns a pointer to a string with the fine-grained UTC time in hh:mm:ss.ssssss format.
Based on gf_time() from Stevens, W.R., 1998, Unix Network Programming, Vol 2, Prentice Hall, Figure 15.6, but I make a string with an ISO8601 compliant format.
Of course, while it may return microsecond precision, microsecond accuracy is quite another thing...
Referenced by main().
main()
int main (int argc, char * argv[])
References getDateTime(), MAX_TABLINES, and StrUpper().