mmcService - Interactive MODS Mechanism Control System: mmcService.c File Reference
mmcService.c File Reference
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/timeb.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <string.h>
#include <fcntl.h>
#include <signal.h>
#include <errno.h>
#include <unistd.h>
#include "mmc_client.h"
#include "instrutils.h"
#include "isl_funcs.h"
#include "isl_types.h"
#include "params.h"
#include "islcommon.h"
#include "isl_shmaddr.h"
Data Structures
struct Thread
struct agw_errors
Macros
#define MAX_CLIENT_PER_THREAD 64
#define MAX_THREAD 100
#define PORT 10435
#define PROMPT "M1%"
Functions
int wagoSetGet (int, char[], int, int, short int *, int)
int getWagoID (char[], char[])
Get the WAGO ID from Shared Memory.
int isisStatusMsg (char[])
Status message for request Agent.
void sig_chld (int)
int mmcLOGGER (char[], char[])
void * thread_init_func (void *)
void nonblock (int sockfd)
char * getDateTime (void)
Return the UTC date/time as an ISO 8601 coded string.
int choose_thread ()
int main (int argc, char *argv[])
void HandleInt (int signalValue)
Variables
struct islcommon * mechs
char buf [ISIS_MSGSIZE]
char tempbuf [80]
isisclient_t appClient
isisclient_t client
struct sockaddr_in srv cli
char timestr [80]
int cmdCounter
int listenfd
int clifd
fd_set read_fd
int charReceived
int readFromListen_port
char getset_reply [ISIS_MSGSIZE]
int allPower
agw_errors errmsgs
pthread_cond_t new_connection_cond = PTHREAD_COND_INITIALIZER
pthread_mutex_t new_connection_mutex = PTHREAD_MUTEX_INITIALIZER
Thread threads [MAX_THREAD]
Macro Definition Documentation
MAX_CLIENT_PER_THREAD
#define MAX_CLIENT_PER_THREAD 64
MAX_THREAD
#define MAX_THREAD 100
PORT
#define PORT 10435
PROMPT
#define PROMPT "M1%"
Function Documentation
wagoSetGet()
int wagoSetGet (int , char [], int , int , short int * , int)
Referenced by main().
getWagoID()
int getWagoID (char wagoid_name[], char dummy[])
Get the WAGO ID from Shared Memory.
Parameters
dummy wago id
reply reply message
Returns
wagoID or error
Get WAGO ID
References makeUpper().
Referenced by cmd_irlaser(), cmd_istatus(), cmd_lamp(), cmd_misc(), cmd_power65(), cmd_vislaser(), and main().
isisStatusMsg()
int isisStatusMsg (char dummy[])
Status message for request Agent.
Parameters
dummy message string
Returns
The value of -1 is error
Sends status information
References client, ierr, and who_srcID.
Referenced by agwProbe(), agwRestore(), Calib(), cmd_minsert(), cmd_misc(), cmd_mselect(), cmd_slitmask(), Hatch(), main(), and thread_init_func().
sig_chld()
void sig_chld (int signo)
Referenced by main().
mmcLOGGER()
int mmcLOGGER (char [], char [])
Referenced by HandleInt(), main(), nonblock(), and thread_init_func().
thread_init_func()
void * thread_init_func (void * arg)
References appClient, buf, charReceived, client, Thread::client_count, Thread::clients, clifd, agw_errors::err_cnt, errmsgs, agw_errors::errors, getDateTime(), getMechanismID(), getset_reply, ierr, isisStatusMsg(), KeyCommand(), LoadConfig(), MAX_CLIENT_PER_THREAD, mmcLOGGER(), rawCommand(), readFromListen_port, SocketCommand(), tempbuf, and threads.
Referenced by main().
nonblock()
void nonblock (int sockfd)
References mmcLOGGER().
getDateTime()
char* getDateTime (void)
Return the UTC date/time as an ISO 8601 coded string.
Reads the system time clock and returns the UTC date and time coded as an ASCII string in ISO 6801 compliant format (www.iso.org/iso/iso8601). The UTC clock time is expressed to microsecond precision (we make no claims to microsecond accuracy - YMMV). For example
  2013-05-26T12:07:58.114391
Return the UTC date/time as an ISO 8601 coded string.
Reads the system's UTC time clock and returns a pointer to a string with the fine-grained UTC time in hh:mm:ss.ssssss format.
Based on gf_time() from Stevens, W.R., 1998, Unix Network Programming, Vol 2, Prentice Hall, Figure 15.6, but I make a string with an ISO8601 compliant format.
Of course, while it may return microsecond precision, microsecond accuracy is quite another thing...
Referenced by HandleInt(), main(), mmcLOGGER(), and thread_init_func().
choose_thread()
int choose_thread ()
References MAX_THREAD, and threads.
Referenced by main().
main()
int main (int argc, char * argv[])
References allPower, buf, charReceived, choose_thread(), cli, client, Thread::client_count, Thread::clients, clifd, cmdCounter, agw_errors::err_cnt, errmsgs, getWagoID(), HandleInt(), ieb1ID, ieb2ID, isisStatusMsg(), listenfd, llbID, LoadConfig(), MAX_CLIENT_PER_THREAD, MAX_THREAD, mmcLOGGER(), new_connection_mutex, PORT, read_fd, readFromListen_port, sig_chld(), thread_init_func(), threads, Thread::tid, utilID, and wagoSetGet().
HandleInt()
void HandleInt (int signalValue)
References buf, client, Thread::client_count, Thread::clients, clifd, MAX_THREAD, mmcLOGGER(), and threads.
Referenced by main().
Variable Documentation
mechs
struct islcommon* mechs
buf
char buf[ISIS_MSGSIZE]
Referenced by HandleInt(), main(), SocketCommand(), and thread_init_func().
tempbuf
char tempbuf[80]
Referenced by thread_init_func().
appClient
isisclient_t appClient
Referenced by thread_init_func().
client
isisclient_t client
Referenced by cmd_debug(), cmd_info(), cmd_pong(), cmd_quit(), cmd_verbose(), HandleInt(), isisStatusMsg(), KeyCommand(), LoadConfig(), main(), SocketCommand(), and thread_init_func().
cli
struct sockaddr_in srv cli
Referenced by main().
timestr
char timestr[80]
Referenced by mmcLOGGER().
cmdCounter
int cmdCounter
Referenced by main().
listenfd
int listenfd
Referenced by main().
clifd
int clifd
Referenced by HandleInt(), main(), and thread_init_func().
read_fd
fd_set read_fd
Referenced by main().
charReceived
int charReceived
Referenced by main(), and thread_init_func().
readFromListen_port
int readFromListen_port
Referenced by main(), and thread_init_func().
getset_reply
char getset_reply[ISIS_MSGSIZE]
Referenced by thread_init_func().
allPower
int allPower
Referenced by main().
errmsgs
agw_errors errmsgs
Referenced by main(), and thread_init_func().
new_connection_cond
pthread_cond_t new_connection_cond = PTHREAD_COND_INITIALIZER
new_connection_mutex
pthread_mutex_t new_connection_mutex = PTHREAD_MUTEX_INITIALIZER
Referenced by main().
threads
Thread threads[MAX_THREAD]
Referenced by choose_thread(), HandleInt(), main(), and thread_init_func().