AGWSim - Interactive MODS AGW Simulator Agent: agwServer.c File Reference
agwServer.c File Reference
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/timeb.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <string.h>
#include <fcntl.h>
#include <signal.h>
#include <errno.h>
#include <unistd.h>
#include "../include/client.h"
#include "../include/mods_timefuncts.h"
#include "isisclient.h"
#include "instrutils.h"
#include "isl_funcs.h"
#include "isl_types.h"
#include "params.h"
#include "islcommon.h"
#include "isl_shmaddr.h"
Data Structures
struct Thread
struct agw_errors
Macros
#define MAX_CLIENT_PER_THREAD 12
#define MAX_THREAD 12
#define PORT 10433
#define PROMPT "AGW>"
Functions
void sig_chld (int)
int mmcLOGGER (char[], char[])
char * makeUpper (char[])
Return uppercase string.
void * thread_init_func (void *)
void nonblock (int sockfd)
int choose_thread ()
int main (int argc, char *argv[])
void HandleInt (int signalValue)
Variables
struct islcommon * agws
char buf [ISIS_MSGSIZE]
isisclient_t appClient
struct sockaddr_in srv cli
agwpar_t appAGW
int listenfd
int clifd
fd_set read_fd
int charReceived
int readFromListen_port
char buffer [ISIS_MSGSIZE]
agw_errors errmsgs
pthread_cond_t new_connection_cond = PTHREAD_COND_INITIALIZER
pthread_mutex_t new_connection_mutex = PTHREAD_MUTEX_INITIALIZER
Thread threads [MAX_THREAD]
Macro Definition Documentation
MAX_CLIENT_PER_THREAD
#define MAX_CLIENT_PER_THREAD 12
MAX_THREAD
#define MAX_THREAD 12
PORT
#define PORT 10433
PROMPT
#define PROMPT "AGW>"
Function Documentation
sig_chld()
void sig_chld (int signo)
Referenced by main().
mmcLOGGER()
int mmcLOGGER (char [], char [])
Referenced by HandleInt(), main(), and thread_init_func().
makeUpper()
char* makeUpper (char str2[])
Return uppercase string.
Parameters
str2 string remains unchanged.
str returned as uppercase string,
Helper utility will return requested string in uppercase, and leave the requested string unchanged.
Referenced by checkPower(), closeCommand(), getMechanismID(), mlcActivePorts(), mlcBusy(), mlcCheckBits(), mlcLimitBits(), mlcStopMechanism(), mlcWhoAmI(), openCommand(), positionToShrMem(), rawCommand(), rawCommandOnly(), sendCommand(), sendMultiCommand(), and sendTwoCommand().
thread_init_func()
void * thread_init_func (void * arg)
References appAGW, appClient, buffer, Thread::client_count, Thread::clients, errmsgs, agw_errors::errors, GCSCommand(), getCurrentTime(), LoadConfig(), MAX_CLIENT_PER_THREAD, mmcLOGGER(), readFromListen_port, and threads.
Referenced by main().
nonblock()
void nonblock (int sockfd)
choose_thread()
int choose_thread ()
References MAX_THREAD, and threads.
Referenced by main().
main()
int main (int argc, char * argv[])
References appAGW, appClient, buf, buffer, choose_thread(), cli, Thread::client_count, Thread::clients, clifd, agw_errors::err_cnt, errmsgs, agw_errors::errors, HandleInt(), listenfd, LoadConfig(), MAX_CLIENT_PER_THREAD, MAX_THREAD, mmcLOGGER(), new_connection_mutex, PORT, read_fd, readFromListen_port, sig_chld(), thread_init_func(), and threads.
HandleInt()
void HandleInt (int signalValue)
References appClient, buf, Thread::client_count, Thread::clients, clifd, MAX_THREAD, mmcLOGGER(), and threads.
Referenced by GCSCommand(), and main().
Variable Documentation
agws
struct islcommon* agws
buf
char buf[ISIS_MSGSIZE]
Referenced by HandleInt(), main(), and SocketCommand().
appClient
isisclient_t appClient
Referenced by cmd_ccdAgwSfp(), cmd_debug(), cmd_info(), cmd_noop(), cmd_pong(), cmd_quit(), cmd_verbose(), HandleInt(), main(), SocketCommand(), and thread_init_func().
cli
struct sockaddr_in srv cli
Referenced by main().
appAGW
agwpar_t appAGW
Referenced by agwFocus(), cmd_abort(), cmd_agw(), cmd_autofoc(), cmd_calib(), cmd_ccdAgwSfp(), cmd_center(), cmd_drift(), cmd_driftvec(), cmd_filter(), cmd_focus(), cmd_foffset(), cmd_getpos(), cmd_home(), cmd_info(), cmd_init(), cmd_lock(), cmd_mmccu(), cmd_mmcIC(), cmd_reset(), cmd_setpos(), cmd_status(), cmd_unlock(), cmd_xy(), main(), SocketCommand(), and thread_init_func().
listenfd
int listenfd
Referenced by main().
clifd
int clifd
Referenced by HandleInt(), and main().
read_fd
fd_set read_fd
Referenced by main().
charReceived
int charReceived
readFromListen_port
int readFromListen_port
Referenced by main(), and thread_init_func().
buffer
char buffer[ISIS_MSGSIZE]
Referenced by main(), and thread_init_func().
errmsgs
agw_errors errmsgs
Referenced by main(), and thread_init_func().
new_connection_cond
pthread_cond_t new_connection_cond = PTHREAD_COND_INITIALIZER
new_connection_mutex
pthread_mutex_t new_connection_mutex = PTHREAD_MUTEX_INITIALIZER
Referenced by main().
threads
Thread threads[MAX_THREAD]
Referenced by choose_thread(), HandleInt(), main(), and thread_init_func().