AGWSim - Interactive MODS AGW Simulator Agent: loadconfig.c File Reference
loadconfig.c File Reference
Load/Parse ISIS client's runtime configuration file.
#include "../include/client.h"
Macros
#define MAXCFGLINE 80
Maximum mumber of characters/line in the runtime config file.
Functions
int LoadConfig (agwpar_t *agw, isisclient_t *client, char *cfgfile)
Load/Parse ISIS client's runtime configuration file.
Detailed Description
Load/Parse ISIS client's runtime configuration file.
ISIS-style runtime configuration files (e.g., named myclient.ini, .myclientrc, whatever) contain simple Keyword-Value pairs that are parsed into global-scope variables for the client and its various subroutines to use.
The # is used as a comment character, making a comment line when it appears as the first character in a line by itself. Inline comments are not supported by this simple parser, but are generally ignored since it assumes (again for simplicity) that value arguments are numbers or strings without spaces. Fancier parsers can be implemented as needed. Blank lines are ignored by the parser. We adopt the convention that keywords and values are case insensitive, to remove any ambiguity.
This template provides a good example of common client initialiation file parameters and syntax. The idea is to make the runtime config files for all ISIS clients look pretty much the same in terms of having a common syntax as appearance. The utility function GetArg() used here is from isisutils.c, with the prototype defined in the isisclient.h header.
A typical runtime config file has the following structure:
#
# myclient runtime configuration file
#
# Modified 2003 June 21 by R. Pogge, OSU Astronomy Dept.
# for the fauxMODS spectrograph system echoclient.
#
ID  echo
Port 7890
Verbose
#
ServerID   isis1
ServerHost mods1.lbto.org
ServerPort 6789
#
Filter 1 Blue
Filter 2 SDSS i
Filter 3 SDSS g
Filter 4 Clear
#
XCenter   92000
YCenter  202000
Focus0    42000
WFSXOffset    0
WFSYOffset 1234
#
Here we are telling myclient that it is a client of an ISIS server named "isis1" running on host mods1.lbto.org and listening to network socket port 6789. We are to be an ISIS client node named "echo" listing to network socket port 7890 on the localhost. All runtime logging will be recorded to a file named /data/Logs/myclient.log, and both logging and screen output will be Verbose for debugging purposes.
As this example shows, the goal is that runtime configuration files are easily read and created by humans. A common syntax makes maintenance of many clients easier.
This version is custom for the agwsim application.
Author
R. Pogge, OSU Astronomy Dept. (pogge.nosp@m.@ast.nosp@m.ronom.nosp@m.y.oh.nosp@m.io-st.nosp@m.ate..nosp@m.edu)
Date
2003 September 14 (original version based on the ISIS server ParseIniFile())
Mods Modification History:
   2006 Feb 07 - implemented filter ID table [rwp/osu]
   2008 Jan 24 - various changes for the actual AGW stage system [rwp/osu]
   2008 Aug 19 - overhauled to remove sim mode and other changes [rwp/osu]
Macro Definition Documentation
MAXCFGLINE
#define MAXCFGLINE 80
Maximum mumber of characters/line in the runtime config file.
Function Documentation
LoadConfig()
int LoadConfig (agwpar_t * agw, isisclient_t * client, char * cfgfile)
Load/Parse ISIS client's runtime configuration file.
Parameters
agw pointer to the agwpar_t for this AGW instance
client pointer to the isisclient_t for this app instance
cfgfile Path/name of the client runtime configuration file
Returns
0 if success, <0 if failure. All error message are printed to the client's console.
The precise actions of LoadConfig() are tailored to the client application.
References agw, agwInitConfig(), argbuf, and MAXCFGLINE.
Referenced by cmd_ccdAgwSfp(), main(), and thread_init_func().