AGWSim - Interactive MODS AGW Simulator Agent: mmcLOGGER.c File Reference
mmcLOGGER.c File Reference
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <sys/sendfile.h>
#include "isisclient.h"
#include "instrutils.h"
#include "isl_funcs.h"
#include "isl_types.h"
#include "params.h"
#include "islcommon.h"
#include "isl_shmaddr.h"
Functions
int getCurrentTime (char *, char *)
char * getDateTime (void)
Return the UTC date and time to microsecond precision as a system timestamp.
int mmcLOGGER (char path[79], char msg[512])
mmcService Logger
int mmcSaveConfig (char path[79], char mmcData[])
mmcSaveConfig save MODS configuration
int mmcGetConfig (char path[79], char mmcData[])
mmcGetConfig get the last MODS configuration
Function Documentation
getCurrentTime()
int getCurrentTime (char * timestring, char * formatstring)
Referenced by thread_init_func().
getDateTime()
char* getDateTime (void)
Return the UTC date and time to microsecond precision as a system timestamp.
Reads the system's UTC time clock and returns a pointer to a string with the fine-grained UTC time in hh:mm:ss.ssssss format.
Based on gf_time() from Stevens, W.R., 1998, Unix Network Programming, Vol 2, Prentice Hall, Figure 15.6, but I make a string with an ISO8601 compliant format.
Of course, while it may return microsecond precision, microsecond accuracy is quite another thing...
Referenced by mmcLOGGER().
mmcLOGGER()
int mmcLOGGER (char path[79], char msg[512])
mmcService Logger
Reads system's UTC time with getDataTime() function and logs Service infomation to mmcLogging.log
References getDateTime().
mmcSaveConfig()
int mmcSaveConfig (char path[79], char mmcData[])
mmcSaveConfig save MODS configuration
Reads system's UTC time with getDataTime() function and logs Service infomation to mmcSaveConfig.dat
mmcGetConfig()
int mmcGetConfig (char path[79], char mmcData[])
mmcGetConfig get the last MODS configuration
Reads system's UTC time with getDataTime() function and logs Service infomation to modsConfig_1.dat