#
foo: ./build
	./build
clean: ./build 
	./build clean
execs: ./build 
	./build execs
install: ./build 
	./build install
installsim: ./build 
	./build installsim
sim: ./build 
	./build simulator
dist: ./build 
	./build dist
all: ./build 
	./build all
#
