AGW - Interactive MODS AGW Control Agent: islAPIInit.c File Reference
islAPIInit.c File Reference
#include "islapi.h"
#include <stdio.h>
Functions
void islAPIInit (void)
Variables
pthread_mutex_t islWaitContact_mutex = PTHREAD_MUTEX_INITIALIZER
pthread_mutex_t cname_mutex = PTHREAD_MUTEX_INITIALIZER
pthread_mutex_t appname_mutex = PTHREAD_MUTEX_INITIALIZER
int initapi = 0
Function Documentation
islAPIInit()
void islAPIInit (void)
References initapi.
Referenced by islAppNameToAppNumb(), islCnameToComp(), islMakeContact(), and islWaitContact().
Variable Documentation
islWaitContact_mutex
pthread_mutex_t islWaitContact_mutex = PTHREAD_MUTEX_INITIALIZER
Referenced by islWaitContact().
cname_mutex
pthread_mutex_t cname_mutex = PTHREAD_MUTEX_INITIALIZER
Referenced by islCnameToComp().
appname_mutex
pthread_mutex_t appname_mutex = PTHREAD_MUTEX_INITIALIZER
Referenced by islAppNameToAppNumb().
initapi
int initapi = 0
Referenced by islAPIInit().