#!/bin/csh
#

setenv CDATE `date +'%Y-%b-%d'`
setenv CTIME `date +'%T'`
#
# remove all dotos and executables
make -f Makefile.build clean
#
# compile with time and date of compile
make -f Makefile.build "COMPDATE=$CDATE" "COMPTIME=$CTIME"
\mv *.o ../obj
\cp ../obj/* /home/dts/mods/obj/.
exit
# Thank you
