#!/bin/bash

tmuxID="ccdTerm"
modsHost="${HOSTNAME^^}"
modsChan="red"
modsID="${modsHost} Red"

# Check if the session already exists

tmux has-session -t $tmuxID 2>/dev/null

if [ $? != 0 ]; then
  # Create a new detached session

  tmux -f ~/.tmux.conf.$modsChan new-session -d -s $tmuxID

  # Create a new window (if needed) and name it

  tmux new-window -t $tmuxID:1 -n "${modsID} CCD Controller Admin"

  # Split the window into panes (optional, adjust as needed)

  tmux split-window -v -p 5  # split bottom pane shorter
  tmux split-window -h -p 50 -t $tmuxID:1.0 # Split horizontally

  # Pane decor

  tmux set -g pane-border-status top
  tmux set -g pane-border-format " #{pane_title} "

  tmux select-pane -t $tmuxID:1.0 -T "modsCCD"
  tmux select-pane -t $tmuxID:1.1 -T "azcam Server"
  tmux select-pane -t $tmuxID:1.2 -T "Commands"

   # aliases
   tmux send-keys -t ${tmuxID}:1.0 "source ${configDir}/tmaliases" C-m
   tmux send-keys -t ${tmuxID}:1.1 "source ${configDir}/tmaliases" C-m
   tmux send-keys -t ${tmuxID}:1.2 "source ${configDir}/tmaliases" C-m

  # programs to launch in panes...

  # tmux send-keys -t $tmuxID:1.0 "start_modsCCD" C-m # run the modsCCD agent in the top left pane
  # tmux send-keys -t $tmuxID:1.1 "start_azcam" C-m # run the azcam server in the top right pane

fi

# If we're already in the expected tmux session, do nothing
# otherwise attach to the command pane (1.2)

if [ -n "$TMUX" ]; then
   echo "Currently in the ${tmuxID} session"
else
   resize -s 42 128 &> /dev/null
   tmux select-pane -t ${tmuxID}:1.2
   tmux attach-session -t ${tmuxID}
fi
