#!/bin/csh -f
#
# modsTerm - start MODS binocular observing script session
#
# This script launches a named tmux session that will be used to execute
# MODS binocular science target acquisition and observation scripts.
#
# While it may be invoked by itself, if the session is not running
# it will be executed by the acqBinoMODS and execBinoMODS scripts.
#
# The modsTerm tmux session is configured with 3 window panes
# 
#      +---------------------+---------------------+
#      |        MODS1        |        MODS2        |
#      |         1.0         |         1.1         |
#      |                     |                     |
#      |                     |                     |
#      |                     |                     |
#      +---------------------+---------------------+
#      |                  command                  |
#      |                    1.2                    |
#      +---------------------+---------------------+
#
# Low-level setup is in the $configDir/tmux_mods.conf file.
# Also defines and exports aliases to the bash shell to make
# detachment by "detach" or "quit" and throttling "exit"
#
# R. Pogge (pogge.1@osu.edu)
# OSU Astronomy Department
# 2025 Oct 4 - Alpha version
#
# Modification History:
#
#---------------------------------------------------------------------------

set tmuxID = "modsTerm"

# LBTO Public executable path

setenv modsDir /lbt/lbto/mods
setenv configDir /lbt/lbto/mods/.config

# Parse the command-line options

tmux has-session -t $tmuxID >& /dev/null
if ($status) then
   tmux -f ${configDir)/tmux_mods.conf new-session -d -s $tmuxID
   tmux new-window -t ${tmuxID}:1 -n "MODS Binocular Observing"
   tmux split-window -v -p 5  
   tmux split-window -h -p 50 -t ${tmuxID}:1.0
   # pane IDs
   tmux set -g pane-border-status top
   tmux set -g pane-border-format " #{pane_title} "
   tmux select-pane -t ${tmuxID}:1.0 -T "MODS1"
   tmux select-pane -t ${tmuxID}:1.1 -T "MODS2"
   tmux select-pane -t ${tmuxID}:1.2 -T "Commands"
endif

# If we're already in the expected tmux session, do nothing
# otherwise attach to the command pane (1.2)

if ( ! $?TMUX) then
   tmux select-pane -t ${tmuxID}:1.2
   tmux attach-session -t ${tmuxID}
endif   

exit 0
