#!/bin/csh -f
#
echo "osu1 and lbt1 = MODS1 mechanisms"
echo "osu2 and lbt2 = MODS2 mechanisms"
echo -n "Change mechanisms.ini link to: osu1, osu2, lbt1, lbt2: "

set reply = $<
#
if ( $reply == "osu1" ) then
    rm mechanisms.ini
#    ln -sfn /home2/mods/Config/OSU/mechanisms_MODS1.ini mechanisms.ini
    ln -sfn $PWD/OSU/mechanisms_MODS1.ini mechanisms.ini
    echo "You have selected: "; ls -og mechanisms.ini

else if ( $reply == "osu2" ) then
    rm mechanisms.ini
#    ln -sfn /home2/mods/Config/OSU/mechanisms_MODS2.ini mechanisms.ini
    ln -sfn $PWD/OSU/mechanisms_MODS2.ini mechanisms.ini
    echo "You have selected: "; ls -og mechanisms.ini

else if ( $reply == "lbt1" ) then
    rm mechanisms.ini
#    ln -sfn /home2/mods/Config/LBTO/mechanisms_MODS1.ini mechanisms.ini
    ln -sfn $PWD/LBTO/mechanisms_MODS1.ini mechanisms.ini
    echo "You have selected: "; ls -og mechanisms.ini

else if ( $reply == "lbt2" ) then
    rm mechanisms.ini
#    ln -sfn /home2/mods/Config/LBTO/mechanisms_MODS2.ini mechanisms.ini
    ln -sfn $PWD/LBTO/mechanisms_MODS2.ini mechanisms.ini
    echo "You have selected: "; ls -og mechanisms.ini
else then
    rm mechanisms.ini
    ln -sfn $PWD/$reply mechanisms.ini
    echo "You have selected a test configuration file: "; ls -og mechanisms.ini

endif
