#!/bin/csh
#
# Poke (query status of) all MODS1 mechanisms via ISIS and the IE
# server.  This is a quick way to check for dangling sockets.
#
# Restrict execution to the ISP user account (lbto)
#
# R. Pogge, OSU Astronomy
#
# Updated: 2025 Oct 14 - Archon controller updates [rwp/osu]
#

set user=`echo $USER | tr '[:upper:]' '[:lower:]'`
if ("${user}" != "lbto") then
   printf "ERROR: User '${user}' is not permitted to run this program.\n"
   printf "       Please ask your ISP for assistance.\n"
   exit 1
endif

set errCount = 0
echo "Poking MODS1 Mechanisms..."
echo "Common focal plane:"
isisCmd --mods1 m1.ie hatch
isisCmd --mods1 m1.ie calib
isisCmd --mods1 m1.ie agwx
isisCmd --mods1 m1.ie agwy
isisCmd --mods1 m1.ie agwfoc
isisCmd --mods1 m1.ie agwfilt
isisCmd --mods1 m1.ie mselect
isisCmd --mods1 m1.ie minsert
isisCmd --mods1 m1.ie dichroic
echo "Blue Channel:"
isisCmd --mods1 m1.ie bcolttfa
isisCmd --mods1 m1.ie bcolttfb
isisCmd --mods1 m1.ie bcolttfc
isisCmd --mods1 m1.ie bgrating
isisCmd --mods1 m1.ie bgrtilt1
isisCmd --mods1 m1.ie bcamfoc
isisCmd --mods1 m1.ie bfilter
echo "Red Channel:"
isisCmd --mods1 m1.ie rcolttfa
isisCmd --mods1 m1.ie rcolttfb
isisCmd --mods1 m1.ie rcolttfc
isisCmd --mods1 m1.ie rgrating
isisCmd --mods1 m1.ie rgrtilt1
isisCmd --mods1 m1.ie rcamfoc
isisCmd --mods1 m1.ie rfilter

echo " "
echo "Done - if any errors or timeouts, correct/reset as needed."
echo " "

exit 0
