######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 23 14:36:28 2009
######################################################################

TEMPLATE = app
TARGET = 
MOC_DIR = moc
OBJECTS_DIR = obj
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += isisclient.h iterm.h console.h texthistentry.h
SOURCES += isisclient.cpp console.cpp main.cpp texthistentry.cpp
RESOURCES += iterm.qrc
QT += network
