AGWSim - Interactive MODS AGW Simulator Agent: agwutils.c File Reference
agwutils.c File Reference
MODS AGW Stage Utility Functions.
#include "../include/client.h"
#include "../include/agwutils.h"
Functions
int mlcBitsBase10 (int, char[], char[])
Check mechanism IO bits.
int agwIsLocked (agwpar_t *agw, char *reply)
Check the AGW lock status.
void agwInitConfig (agwpar_t *agw)
Initialize the AGW stage runtime parameters.
double agwFocus (double xGP, double yGP)
Compute the focus offset at any given guide probe field position.
void gpToAGW (agwpar_t *agw, double xgp, double ygp, double *xs, double *ys, double *foc)
Transform Guide Probe (xGP,yGP) to AGW stage (Xs,Ys,Focus)
void agwToGP (agwpar_t *agw, double xs, double ys, double foc, double *xgp, double *ygp)
Transform AGW stage (Xs,Ys,Focus) to Guide Probe (xGP,yGP)
void agwGetPos (agwpar_t *agw)
Query the mechanisms and update the device position data members.
Detailed Description
MODS AGW Stage Utility Functions.
This module contains utility functions used by the MODS AGW stage control system.
Author
R. Pogge, OSU Astronomy Dept. (pogge.nosp@m.@ast.nosp@m.ronom.nosp@m.y.oh.nosp@m.io-st.nosp@m.ate..nosp@m.edu)
Date
2006 Jan 12
Modification History:
   2008 Jan 27 - various changes for the actual AGW stage system
                 and the simulation modes [rwp/osu]
   2008 Aug 19 - overhauled to update transformations and remove
                 the simulation mode [rwp/osu]
   2009 Oct 24 - modifications while testing the LBT GCS interface [rdg & rwp/osu]
   2010 Mar 10 - replace sendCommand(); with mlcBase10Bits(); for filterwheel[rdg]
   2011 Mar 19 - modify agwFocus() to compute focus at the location of the WFS
                 hotspot [rwp/osu]
Function Documentation
mlcBitsBase10()
int mlcBitsBase10 (int i, char cmd[], char dummy[])
Check mechanism IO bits.
Parameters
i index of the mechanism
cmd IO bit string to convert
dummy string to contain reply if error
Returns
The value of the bits in base 10
Queries the named mechanism for bit value
  Bits 1 - 6 IO 20, and IO 30
References atobase(), and rawCommand().
Referenced by cmd_filter(), cmd_getpos(), cmd_home(), cmd_init(), cmd_reset(), cmd_setpos(), cmd_xy(), and mlcLimitBits().
agwIsLocked()
int agwIsLocked (agwpar_t * agw, char * reply)
Check the AGW lock status.
Parameters
agw pointer to an agwpar_t struct for this AGW instance
reply string to contain any command return reply
Returns
1 if the AGW is locked against this host, 0 if the AGW is either (a) not locked or (b) host is the lock holder. The reply string contains an error message if the host is locked out.
Tests the status of the AGW command lock. If the lock is not set, it returns 0, allowing the action function (usually in command.c) to proceed. If the lock is asserted, it tests the cmdHost against lockHost. If cmdHost is the lockHost it returns 0 ("OK to proceed"), otherwise it returns 1 ("device is locked out").
Allowance for executive override must be tested in the calling routine.
References agw.
Referenced by cmd_autofoc(), cmd_center(), cmd_drift(), cmd_driftvec(), cmd_filter(), cmd_focus(), cmd_foffset(), cmd_home(), cmd_setpos(), and cmd_xy().
agwInitConfig()
void agwInitConfig (agwpar_t * agw)
Initialize the AGW stage runtime parameters.
Parameters
agw pointer to the agwpar_t struct to initialize
Initializes the AGW stage configuration data structure to sensible default values.
References agw, and agwToGP().
Referenced by LoadConfig().
agwFocus()
double agwFocus (double xGP, double yGP)
Compute the focus offset at any given guide probe field position.
Parameters
xGP X-axis location of the guide probe center in millimeters
yGP Y-axis location of the guide probe center in millimeters
Returns
The focus value in millimeters from the focus home position
The LBT f/15 Direct Gregorian focus has a convex spherical focal surface with the tangent point located at the center of the MODS science field. The radius of curvature of this surface is defined by #AGW_FRADIUS in millimeters.
For any given guide probe position relative to the science field center, this routine computes the nominal focus offset.
Note that this routine just does the formal calculation of the focus surface, it does not validate the computed offset against the permitted range of motion of the focus mechanism. That is the ultimate responsibility of the calling routine.
Because the WFS pickoff is not located at the center of the guider field-of-view, we need to compute the focus at the location of the WFS "hotspot", which is defined in the .ini file by the WFSXOffset and WFSYOffset parameters. This offset must be measured for each AGw unit, and can change when the AGw units are serviced.
The telescope active optics is sensitive enough to see the focus difference. For example, for a WFS Y-offset of 13.5mm relative to the center of the guide camera, at Y=4-arcmin from the science field center the focus shift is -1.8mm, corresponding to -298nm of Z4 shift (focus Zernike term). This is readily measurable by the LBT active optics system.
This change was instituted on 2011 March 19 [rwp/osu]
References appAGW.
Referenced by gpToAGW().
gpToAGW()
void gpToAGW (agwpar_t * agw, double xgp, double ygp, double * xs, double * ys, double * foc)
Transform Guide Probe (xGP,yGP) to AGW stage (Xs,Ys,Focus)
Parameters
agw Pointer to an AGW stage data structure
xgp Guide Probe X coordinate relative to science field center [mm]
ygp Guide Probe Y coordinate relative to science field center [mm]
xs AGW stage X position relative to home [mm]
ys AGW stage Y position relative to home [mm]
foc AGW stage focus probe position relative to home [mm]
For the AGW stage, home is defined as the mechanism driven to its mechanical home position sensor.
The X stage position is just the requested X probe position relative to the calibrated X stage position of the field center.
The Y stage position transformation includes the calibrated Y stage position of the field center and the position of the focus actuator, which is colinear with the Y stage motion. The focal surface of the LBT f/15 direct Gregorian focus is spherical, and computed using agwFocus(). At each Y position, we compute the focus offset associated with that position, and then offset the Y stage that amount to put the guide probe field center at that position, with that focus.
If autoFocus is disabled, it uses the current focus position. In normal operation we expect autoFocus to always be enabled.
Complicated, but it works.
For the reverse transformation, see agwToGP()
References agw, and agwFocus().
Referenced by cmd_center(), and cmd_xy().
agwToGP()
void agwToGP (agwpar_t * agw, double xs, double ys, double foc, double * xgp, double * ygp)
Transform AGW stage (Xs,Ys,Focus) to Guide Probe (xGP,yGP)
Parameters
agw Pointer to an AGW stage data structure
xs AGW stage X position relative to home [mm]
ys AGW stage Y position relative to home [mm]
foc AGW stage focus probe position relative to home [mm]
xgp Guide Probe X coordinate relative to science field center [mm]
ygp Guide Probe Y coordinate relative to science field center [mm]
Transforms the AGW stage position defined by the triplet (Xs,Ys,Focus) into the location of the guide probe field center (xGP,yGP) relative to the defined center of the science field.
For the reverse transformation, see gpToAGW()
References agw.
Referenced by agwGetPos(), and agwInitConfig().
agwGetPos()
void agwGetPos (agwpar_t * agw)
Query the mechanisms and update the device position data members.
Parameters
agw Pointer to an AGW stage data structure
Queries the AGW stage mechanisms and updates the current coordinates of the stage, guide probe center, and WFS pickoff center. The origin of the guide probe and WFS pickoff fields is the nominal center of the MODS science field of view.
Queries the individual mechanism controllers for the current position. All positions are stored internally in units of millimeters.
References agw, agwToGP(), and positionToShrMem().
Referenced by cmd_center(), cmd_focus(), cmd_foffset(), cmd_home(), and cmd_xy().