Serial (TTY) Port I/O API: initTrans.c File Reference
initTrans.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include <sys/types.h>
#include <signal.h>
#include "../include/islapi.h"
#include "../include/modscontrol.h"
#include "../include/getErrorMsg.h"
Macros
#define BUFFSIZE 512
Functions
void GetArgs (char *cmdstr, int argnum, char *argstr)
int initTrans (char *host, int agw_no, struct sac_xy *sacxy)
Variables
sac_xy xy
Macro Definition Documentation
BUFFSIZE
#define BUFFSIZE 512
Function Documentation
GetArgs()
void GetArgs (char * cmdstr, int argnum, char * argstr)
Referenced by initTrans().
initTrans()
int initTrans (char * host, int agw_no, struct sac_xy * sacxy)
References BUFFSIZE, GetArgs(), and mods_fatalerrormsg.
Referenced by mods_init(), and mods_initTrans().
Variable Documentation
xy
sac_xy xy extern