Serial (TTY) Port I/O API: mods_initTrans.c File Reference
mods_initTrans.c File Reference
Client for obtaining the initializing transformation coefficients.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include <sys/types.h>
#include <signal.h>
#include "../include/islapi.h"
#include "../include/modscontrol.h"
Macros
#define BUFFSIZE 512
Functions
void GetArgs (char *cmdstr, int argnum, char *argstr)
int mods_initTrans (char *host, int agw_no, struct sac_xy *sacxy)
Variables
char * mods_fatalerrormsg []
sac_xy xy
Detailed Description
Client for obtaining the initializing transformation coefficients.
Macro Definition Documentation
BUFFSIZE
#define BUFFSIZE 512
Function Documentation
GetArgs()
void GetArgs (char * cmdstr, int argnum, char * argstr)
Referenced by AGWtoSFP(), CCDtoAGW(), CCDtoSFP(), mods_initTrans(), and SFPtoAGW().
mods_initTrans()
int mods_initTrans (char * host, int agw_no, struct sac_xy * sacxy)
References BUFFSIZE, GetArgs(), and mods_fatalerrormsg.
Referenced by mods_inittrans().
Variable Documentation
mods_fatalerrormsg
char* mods_fatalerrormsg[] extern
Referenced by mods_initTrans().
xy
sac_xy xy extern
Referenced by mods_AGWToSFP(), mods_CCDToAGW(), mods_CCDToSFP(), mods_initTrans(), and mods_SFPToAGW().