#!/bin/bash
#
# ccdTerm - start MODS binocular observing script session
#
# This script launches a named tmux session that will be used to execute
# MODS binocular science target acquisition and observation scripts.
#
# While it may be invoked by itself, if the session is not running
# it will be executed by the acqBinoMODS and execBinoMODS scripts.
#
# The ccdTerm tmux session is configured with 3 window panes
# 
#      +---------------------+---------------------+
#      |         1.0         |         1.1         |
#      |       modsCCD       |        azcam        |
#      |                     |                     |
#      |                     |                     |
#      |                     |                     |
#      +---------------------+---------------------+
#      |                  command                  |
#      |                    1.2                    |
#      +---------------------+---------------------+
#
# Low-level setup is in the $configDir/.tmux.conf.blue or .tmux.conf.red
# file, depending on the channel.  Because we are running on the
# MODS servers, the detach, quit, and throttled exit alias are
# defined for the login shell.
#
# R. Pogge (pogge.1@osu.edu)
# OSU Astronomy Department
# 2025 Oct 4 - Alpha version
#
# Modification History:
#   2025 Oct 13 - beta version, put tmaliases in configDir [rwp/osu]
#   2025 Oct 14 - resize on launch to a good size if needed [rwp/osu]
#   2025 Dec 30 - numerous changes from live testing at LBTO [rwp/osu]
#
#---------------------------------------------------------------------------

tmuxID="ccdTerm"

# MODS server tmux configuration file directory

configDir="/home/dts"

# Which MODS Archon server host are we running on?

modsHost="${HOSTNAME}"

if [[ "$modsHost" == "mods1blue" || "$modsHost" == "mods1red" || "$modsHost" == "mods2blue" || "$modsHost" == "mods2red" ]]; then
    modsID=${modsHost:0:6}   # like mods1b, used by azcam
    modsChan=${modsHost:5:${#modsHost}} # blue or red, for config files
    modsInst=${modsHost:0:5} 
    modsInst=${modsInst^^}   # capitalized MODS instance (MODS1 or MODS2)
    modsName="${modsInst} ${modsChan^}" # for tmux session

else
    printf "ERROR: you cannot run $tmuxID on host $modsHost\n"
    printf "       must be on mods1blue, mods1red, mods2blue, or mods2red\n"
    exit 1
fi

# Check if the session already exists

tmux has-session -t $tmuxID 2>/dev/null

if [ $? != 0 ]; then
  # Create a new detached session

  tmux -f ${configDir}/.tmux.conf.${modsChan} new-session -d -s $tmuxID

  # Create a new window (if needed) and name it

  tmux new-window -t $tmuxID:1 -n "${modsName} CCD Admin"

  # Split the window into panes (optional, adjust as needed)

  tmux split-window -v -p 5  # split bottom pane shorter
  tmux split-window -h -p 50 -t $tmuxID:1.0 # Split horizontally

  # Pane decor

  tmux set -g pane-border-status top
  tmux set -g pane-border-format " #{pane_title} "

  tmux select-pane -t $tmuxID:1.0 -T "modsCCD Agent"
  tmux select-pane -t $tmuxID:1.1 -T "azcam Server"
  tmux select-pane -t $tmuxID:1.2 -T "Commands"

   # aliases
   #tmux send-keys -t ${tmuxID}:1.0 "source ${configDir}/tmaliases" C-m
   #tmux send-keys -t ${tmuxID}:1.1 "source ${configDir}/tmaliases" C-m
   #tmux send-keys -t ${tmuxID}:1.2 "source ${configDir}/tmaliases" C-m

  # programs to launch in panes...
  #
  # launch by hand for now
  #
  
fi

# If we're already in the expected tmux session, do nothing
# otherwise attach to the command pane (1.2)

if [ -n "$TMUX" ]; then
   echo "Currently in the ${tmuxID} session"
else
   resize -s 42 160 &> /dev/null
   tmux select-pane -t ${tmuxID}:1.2
   tmux attach-session -t ${tmuxID}
fi
