#!/bin/csh
#
# starts/stops the IMCS test tools
#
# R. Pogge, OSU Astronomy Dept.
# pogge@astronomy.ohio-state.edu
# 2010 June 9
#
# the LBT version uses the explicit IP of the mods server host, otherwise
# we use the locally-resolved name of the OSU Lab mods server host.
#
#---------------------------------------------------------------------------

set versionID = "1.0.3 (2010-06-09)"

# Common variables

set usageMsg = "imcsTools {start|stop|restart|help} [blue|red]"
set imcsHost = "192.168.139.130"
set imcsUser = "mods"

# Get the command line argument - we will validate it later

if ($#argv == 1) then
   set option = $1
   set mode = "all"
else if ($#argv == 2) then
   set option = $1
   set mode = $2
else
   echo "Usage: ${usageMsg}"
   exit 1
endif

# Perform the requested command

switch ($option)
    case 'help':
    echo " "
    echo "imcsTools - start/stop/restart the MODS IMCS testing tools"
    echo " "
    echo "Usage: ${usageMsg}"
    echo " "
    echo "Options:"
    echo "  start   - start the IMCS programs (QC monitors and gui)"
    echo "  stop    - stop the IMCS programs"
    echo "  restart - restart the IMCS programs"
    echo "  help    - print this message"
    echo " "
    echo "Given without the red or blue qualifier, performs the requested"
    echo "function for both red and blue channels"
    echo " "
    echo "--------------------------------"
    echo "imcsTools v${versionID}"
    echo " "
    exit 0
    breaksw

    case 'start':
    if ($mode == "all") then
       ssh ${imcsUser}@{$imcsHost} -f blueQC
       ssh ${imcsUser}@{$imcsHost} -f redQC
       ssh ${imcsUser}@{$imcsHost} -f bimcsGUI
       ssh ${imcsUser}@{$imcsHost} -f rimcsGUI
    else if ($mode == "blue") then
       ssh ${imcsUser}@{$imcsHost} -f blueQC
       ssh ${imcsUser}@{$imcsHost} -f bimcsGUI
    else if ($mode == "red") then
       ssh ${imcsUser}@{$imcsHost} -f redQC
       ssh ${imcsUser}@{$imcsHost} -f rimcsGUI
    else
       echo "ERROR: Unknown option '${mode}' - Usage: ${usageMsg}"
       exit 1
    endif
    echo " "
    exit 0
    breaksw

    case 'stop':
    if ($mode == "all") then
       ssh ${imcsUser}@{$imcsHost} -f killall blueQC
       ssh ${imcsUser}@{$imcsHost} -f killall redQC
       ssh ${imcsUser}@{$imcsHost} -f killall bimcsGUI
       ssh ${imcsUser}@{$imcsHost} -f killall rimcsGUI
    else if ($mode == "blue") then
       ssh ${imcsUser}@{$imcsHost} -f killall blueQC
       ssh ${imcsUser}@{$imcsHost} -f killall bimcsGUI
    else if ($mode == "red") then
       ssh ${imcsUser}@{$imcsHost} -f killall redQC
       ssh ${imcsUser}@{$imcsHost} -f killall rimcsGUI
    else
       echo "ERROR: Unknown option '${mode}' - Usage: ${usageMsg}"
       exit 1
    endif
    echo " "
    exit 0
    breaksw

    case 'restart':
    echo "Stopping $mode imcsTools..."
    if ($mode == "all") then
       ssh ${imcsUser}@{$imcsHost} -f killall blueQC
       ssh ${imcsUser}@{$imcsHost} -f killall redQC
       ssh ${imcsUser}@{$imcsHost} -f killall bimcsGUI
       ssh ${imcsUser}@{$imcsHost} -f killall rimcsGUI
    else if ($mode == "blue") then
       ssh ${imcsUser}@{$imcsHost} -f killall blueQC
       ssh ${imcsUser}@{$imcsHost} -f killall bimcsGUI
    else if ($mode == "red") then
       ssh ${imcsUser}@{$imcsHost} -f killall redQC
       ssh ${imcsUser}@{$imcsHost} -f killall rimcsGUI
    else
       echo "ERROR: Unknown option '${mode}' - Usage: ${usageMsg}"
       exit 1
    endif
    echo "Starting $mode imcsTools..."
    if ($mode == "all") then
       ssh ${imcsUser}@{$imcsHost} -f blueQC
       ssh ${imcsUser}@{$imcsHost} -f redQC
       ssh ${imcsUser}@{$imcsHost} -f bimcsGUI
       ssh ${imcsUser}@{$imcsHost} -f rimcsGUI
    else if ($mode == "blue") then
       ssh ${imcsUser}@{$imcsHost} -f blueQC
       ssh ${imcsUser}@{$imcsHost} -f bimcsGUI
    else if ($mode == "red") then
       ssh ${imcsUser}@{$imcsHost} -f redQC
       ssh ${imcsUser}@{$imcsHost} -f rimcsGUI
    else
       echo "ERROR: Unknown option '${mode}' - Usage: ${usageMsg}"
       exit 1
    endif
    echo " "
    exit 0
    breaksw

    default:
    echo "ERROR: Unknown option '${option}' - Usage: ${usageMsg}"
    exit 1
    breaksw
endsw

exit 0
