#!/bin/csh
#
# acqBinoMODS - execute binocular MODS acqusition
#
# Usage:
#   acqBinoMODS mods.acq
# or
#   acqBinoMODS mods1.acq mods2.acq
#
# Overview:
#   Executes a binocular MODS acquisition.  acqBinoMODS takes one or
#   two command-line arguments: the name(s) of acquisition script(s) to
#   execute in binocular context.  
#
#   If only one .acq script is given, it is executed on both MODS
#   instruments ("identical twinning").
#
#   If two .acq scripts are given, they are executed on MODS1 and
#   MODS2 in the order MODS1 MODS2.
#
#   In either case, acqBinoMODS launches two standalone terminal
#   windows, and then executes acqMODS with the appropriate
#   command-line options to execute the acq scripts in binocular
#   context.
#
#   Upon successful completion of script execution or upon faults that
#   terminate script execution with errors, the terminal windows for
#   each MODS instance stay up so that the messages may be read by the
#   observer.  Hitting the Enter key will exit the terminal session.
#
# Author:
#   R. Pogge, OSU Astronomy Dept.
#   pogge.1@osu.edu
#   2015 Jan 05
#
# Modification History:
#   2016 Oct 17: First full binocular release for 2016B [rwp/osu]
#
#---------------------------------------------------------------------------

setenv binoBin /home/modseng/bin

if ($#argv == 1) then
   set mods1Script = $1
   set mods2Script = $1
else if ($#argv == 2) then
   set mods1Script = $1
   set mods2Script = $2
else
   printf "\nUsage:\n"
   printf "   acqBinoMODS common.acq\n"
   printf "or\n"
   printf "   acqBinoMODS mods1.acq mods2.acq\n\n"
   exit 0
endif

xterm -T 'MODS1 Acquire' -fn 9x15 -e ${binoBin}/acqMODS --mods1 --bino ${mods1Script} &
xterm -T 'MODS2 Acquire' -fn 9x15 -e ${binoBin}/acqMODS --mods2 --bino ${mods2Script} &

exit 0
