#!/bin/csh
#
# execBinoMODS - execute binocular MODS observations
#
# Usage:
#   execBinoMODS mods.obs
# or
#   execBinoMODS mods1.obs mods2.obs
#
# Overview:
#   Executes a binocular MODS observation.  execBinoMODS takes one or
#   two command-line arguments: the name(s) of observing script(s) to
#   execute in binocular context.  These may be one or two .obs
#   scripts (observation without target acquisition) or one or two
#   .img scripts (imaging scripts that combine target acquisition and
#   observation).  
#
#   If only one .obs/.img script is given, it is executed on both MODS
#   instruments ("identical twinning").
#
#   If two .obs/.img scripts are given, they are executed on MODS1 and
#   MODS2 in the order MODS1 MODS2.  Note that you cannot mix .obs and
#   .img scripts.
#
#   In either case, execBinoMODS launches two standalone terminal
#   windows, and then executes execMODS with the appropriate
#   command-line options to execute the scripts in binocular context.
#
#   Upon successful completion of script execution or upon faults that
#   terminate script execution with errors, the terminal windows for
#   each MODS instance stay up so that the messages may be read by the
#   observer.  Hitting the Enter key will exit the terminal session.
#
# Author:
#   R. Pogge, OSU Astronomy Dept.
#   pogge.1@osu.edu
#   2015 Jan 05
#
# Modification History:
#   2016 Oct 17: First full binocular release for 2016B [rwp/osu]
#
#---------------------------------------------------------------------------

setenv binoBin /home/modseng/bin

if ($#argv == 1) then
   set mods1Script = $1
   set mods2Script = $1
else if ($#argv == 2) then
   set mods1Script = $1
   set mods2Script = $2
else
   printf "\nUsage:\n"
   printf "   execBinoMODS common.obs\n"
   printf "or\n"
   printf "   execBinoMODS mods1.obs mods2.obs\n\n"
   exit 0
endif

xterm -T 'MODS1 Execute' -fn 9x15 -e ${binoBin}/execMODS --mods1 --bino ${mods1Script} &
xterm -T 'MODS2 Execute' -fn 9x15 -e ${binoBin}/execMODS --mods2 --bino ${mods2Script} &

exit 0
