#
foo: ./build
	./build
clean: ./build 
	./build clean
rmexe: ./build 
	./build rmexe
rmdoto: ./build 
	./build rmdoto
libs: ./build 
	./build libs
execs: ./build 
	./build execs
install: ./build 
	./build install
dist: ./build 
	./build dist
all: ./build 
	./build all
#
