ISIS Server: serverlog.c File Reference
serverlog.c File Reference
Routines for creating a server runtime log.
#include "isisserver.h"
Functions
void initLog ()
Initialize the ISIS server runtime log for this session.
int logMessage (char *message)
Append an entry to the server's runtime log with date/time tagging.
Detailed Description
Routines for creating a server runtime log.
Function Documentation
initLog()
void initLog (void)
Initialize the ISIS server runtime log for this session.
Opens the server's runtime log. Log entries are created by the logMessage() function.
References server::dateTag, server::doLogging, getDateTime(), getUTCTime(), isis, isis_FALSE, server::lastDate, server::logDate, server::logFD, server::logFile, server::logRoot, MED_STR_SIZE, noonDateTag(), server::serverID, and UTCDATE.
Referenced by logMessage(), and main().
logMessage()
int logMessage (char * message)
Append an entry to the server's runtime log with date/time tagging.
Parameters
message String with the log entry to append to the log.
Returns
0 if successful, <0 if an error occurred.
Appends the message string given into the server's runtime log, along with a date and time tag. If errors occur, messages are printed on the server's command console.
If the date tag has changed, start a new logfile for a new observing day.
Returns 0 if the logging has been disabled, making it look the same as if the log had been updated.
References BIG_STR_SIZE, server::dateTag, server::doLogging, getDateTime(), getUTCTime(), initLog(), isis, isis_FALSE, server::lastDate, server::logDate, server::logFD, MED_STR_SIZE, noonDateTag(), and UTCDATE.
Referenced by broadcastMessage(), getDateTime(), getFineTime(), handleMessage(), handShake(), initSerialPorts(), isisCommand(), main(), openSocket(), sendMessage(), serialHandler(), socketHandler(), sysTimeStamp(), ttyHandler(), and updateHosts().