site_name: AzCam
site_author: Michael Lesser
site_url: 'https://azcam.readthedocs.io/en/latest/'
docs_dir: docs

# Repository
repo_name: mplesser
repo_url: https://github.com/mplesser/azcam
edit_uri: ""

theme:
  name: material
  palette:
    scheme: indigo
    primary: indigo
    accent: indigo
  logo:
    img/logo.png
  favicon:
    img/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
  features:
    navigation.sections
    navigation.instant
    navigation.tabs
    navigation.tabs.sticky
    navigation.top
    navigation.path
    toc.follow
    toc.integrate
      
plugins:
- search
- autorefs
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          show_root_heading: true
          show_root_full_path: true
          heading_level: 2

extra_css:
  - css/mkdocstrings.css

watch:
  - docs/css
  - docs/autocode

nav:
  - Home: 'index.md'
  - 'api.md'
  - 'commands.md'
  - 'classes.md'
  - 'azcamserver.md'
  - 'autocode.md'
  - 'advanced.md'