#!/bin/bash
#
export IMS_HOME=/home/dts/xander-dev/MODS2025/GUIs/imsTool

export CDATE=`date +'%Y-%b-%d'`
export CTIME=`date +'%T'`
#
file=$IMS_HOME/ims.make   

make -f Makefile.linux $1 "COMPDATE=$CDATE" "COMPTIME=$CTIME"
exit
