#############################################################################
# Makefile for building: imsTool
# Generated by qmake (2.01a) (Qt 4.4.3) on: Mon May 6 17:31:13 2013
# Project:  ims.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.4.3/bin/qmake -unix -o ims.make ims.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.4.3/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.4.3/include/QtCore -I/usr/local/Trolltech/Qt-4.4.3/include/QtCore -I/usr/local/Trolltech/Qt-4.4.3/include/QtNetwork -I/usr/local/Trolltech/Qt-4.4.3/include/QtNetwork -I/usr/local/Trolltech/Qt-4.4.3/include/QtGui -I/usr/local/Trolltech/Qt-4.4.3/include/QtGui -I/usr/local/Trolltech/Qt-4.4.3/include -Imoc -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.4.3/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.4.3/lib -lQtGui -L/usr/local/Trolltech/Qt-4.4.3/lib -L/usr/X11R6/lib -pthread -L/lib -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.4.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = client.cpp \
		main.cpp moc/moc_client.cpp \
		qrc_ims.cpp
OBJECTS       = obj/client.o \
		obj/main.o \
		obj/moc_client.o \
		obj/qrc_ims.o
DIST          = /usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_off.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf \
		ims.pro
QMAKE_TARGET  = imsTool
DESTDIR       = 
TARGET        = imsTool

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: ims.make $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

ims.make: ims.pro  /usr/local/Trolltech/Qt-4.4.3/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_off.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.4.3/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.4.3/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.4.3/lib/libQtNetwork.prl
	$(QMAKE) -unix -o ims.make ims.pro
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_off.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.4.3/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.4.3/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.4.3/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o ims.make ims.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/imsTool1.0.0 || $(MKDIR) obj/imsTool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/imsTool1.0.0/ && $(COPY_FILE) --parents client.h obj/imsTool1.0.0/ && $(COPY_FILE) --parents ims.qrc obj/imsTool1.0.0/ && $(COPY_FILE) --parents client.cpp main.cpp obj/imsTool1.0.0/ && (cd `dirname obj/imsTool1.0.0` && $(TAR) imsTool1.0.0.tar imsTool1.0.0 && $(COMPRESS) imsTool1.0.0.tar) && $(MOVE) `dirname obj/imsTool1.0.0`/imsTool1.0.0.tar.gz . && $(DEL_FILE) -r obj/imsTool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) ims.make


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_client.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_client.cpp
moc/moc_client.cpp: timeMethods.h \
		microLynxErrors.h \
		client.h
	/usr/local/Trolltech/Qt-4.4.3/bin/moc $(DEFINES) $(INCPATH) client.h -o moc/moc_client.cpp

compiler_rcc_make_all: qrc_ims.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ims.cpp
qrc_ims.cpp: ims.qrc \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/local/Trolltech/Qt-4.4.3/bin/rcc -name ims ims.qrc -o qrc_ims.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/client.o: client.cpp client.h \
		timeMethods.h \
		microLynxErrors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/client.o client.cpp

obj/main.o: main.cpp client.h \
		timeMethods.h \
		microLynxErrors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/moc_client.o: moc/moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_client.o moc/moc_client.cpp

obj/qrc_ims.o: qrc_ims.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_ims.o qrc_ims.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ || $(MKDIR) $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/$(QMAKE_TARGET)"
	-strip "$(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ || $(MKDIR) $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ 
	-$(INSTALL_FILE) /home2/mods-2.0.0/modsUI/imsTool/client.cpp $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/
	-$(INSTALL_FILE) /home2/mods-2.0.0/modsUI/imsTool/main.cpp $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/
	-$(INSTALL_FILE) /home2/mods-2.0.0/modsUI/imsTool/client.h $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/
	-$(INSTALL_FILE) /home2/mods-2.0.0/modsUI/imsTool/ims.qrc $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/
	-$(INSTALL_FILE) /home2/mods-2.0.0/modsUI/imsTool/ims.pro $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/
	-$(INSTALL_DIR) /home2/mods-2.0.0/modsUI/imsTool/images $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/client.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/client.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ims.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ims.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/images
	-$(DEL_DIR) $(INSTALL_ROOT)/home2/mods-2.0.0/modsUI/imsTool/[]/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

