#!/bin/csh
#
setenv CDATE `date +'%Y-%b-%d'`
setenv CTIME `date +'%T'`
# Please release me let me go.
# remove all dotos
#make -f Makefile.build clean
# compile with time and date of compile
make -f Makefile.build "COMPDATE=$CDATE" "COMPTIME=$CTIME" $1
#
exit
# Thank you
